/**
 * @file
 */

#include "MinecraftPaletteMap.h"

namespace voxelformat {

#define MCCOLORS { \
	{"air", 0}, \
	{"stone", 1}, \
	{"andesite", 1},  \
	{"seagrass", 2},  \
	{"grass", 2},  \
	{"grass_block", 2},  \
	{"dirt", 3},  \
	{"cobblestone", 4},  \
	{"oak_planks", 5},  \
	{"oak_sapling", 6},  \
	{"bedrock", 7},  \
	{"flowing_water", 8},  \
	{"water", 9},  \
	{"flowing_lava", 10},  \
	{"lava", 11},  \
	{"sand", 12},  \
	{"gravel", 13},  \
	{"gold_ore", 14},  \
	{"iron_ore", 15},  \
	{"coal_ore", 16},  \
	{"oak_log", 17},  \
	{"acacia_leaves", 18},  \
	{"spruce_leaves", 18},  \
	{"oak_leaves", 18},  \
	{"jungle_leaves", 18},  \
	{"birch_leaves", 18},  \
	{"sponge", 19},  \
	{"glass", 20},  \
	{"lapis_ore", 21},  \
	{"lapis_block", 22},  \
	{"dispenser", 23},  \
	{"sandstone", 24},  \
	{"note_block", 25},  \
	{"red_bed", 26},  \
	{"powered_rail", 27},  \
	{"detector_rail", 28},  \
	{"sticky_piston", 29},  \
	{"cobweb", 30},  \
	{"tall_grass", 31},  \
	{"tall_seagrass", 31},  \
	{"dead_bush", 32},  \
	{"piston", 33},  \
	{"piston_head", 34},  \
	{"white_concrete", 35},  \
	{"dandelion", 37},  \
	{"poppy", 38},  \
	{"brown_mushroom", 39},  \
	{"red_mushroom", 40},  \
	{"gold_block", 41},  \
	{"iron_block", 42},  \
	{"smooth_stone_slab", 43},  \
	{"stone_slab", 44},  \
	{"brick_wall", 45},  \
	{"bricks", 45},  \
	{"tnt", 46},  \
	{"bookshelf", 47},  \
	{"mossy_cobblestone", 48},  \
	{"obsidian", 49},  \
	{"torch", 50},  \
	{"fire", 51},  \
	{"spawner", 52},  \
	{"oak_stairs", 53},  \
	{"chest", 54},  \
	{"redstone_wire", 55},  \
	{"diamond_ore", 56},  \
	{"diamond_block", 57},  \
	{"crafting_table", 58},  \
	{"wheat", 59},  \
	{"farmland", 60},  \
	{"furnace", 61},  \
	{"campfire", 62},  \
	{"oak_sign", 63},  \
	{"oak_door", 64},  \
	{"ladder", 65},  \
	{"rail", 66},  \
	{"stone_stairs", 67},  \
	{"oak_wall_sign", 68},  \
	{"lever", 69},  \
	{"stone_pressure_plate", 70},  \
	{"iron_door", 71},  \
	{"oak_pressure_plate", 72},  \
	{"redstone_ore", 73},  \
	{"red_concrete", 74},  \
	{"redstone_wall_torch", 75},  \
	{"redstone_torch", 76},  \
	{"stone_button", 77},  \
	{"snow_block", 78},  \
	{"ice", 79},  \
	{"snow", 80},  \
	{"cactus", 81},  \
	{"clay", 82},  \
	{"bamboo", 83},  \
	{"jukebox", 84},  \
	{"oak_fence", 85},  \
	{"pumpkin", 86},  \
	{"netherrack", 87},  \
	{"soul_sand", 88},  \
	{"glowstone", 89},  \
	{"portal", 90},  \
	{"carved_pumpkin", 91},  \
	{"cake", 92},  \
	{"repeater", 93},  \
	{"skeleton_skull", 94},  \
	{"white_stained_glass", 95},  \
	{"oak_trapdoor", 96},  \
	{"turtle_egg", 97},  \
	{"stone_bricks", 98},  \
	{"brown_mushroom_block", 99},  \
	{"red_mushroom_block", 100},  \
	{"iron_bars", 101},  \
	{"light_blue_stained_glass_pane", 102},  \
	{"melon", 103},  \
	{"pumpkin_stem", 104},  \
	{"melon_stem", 105},  \
	{"vine", 106},  \
	{"oak_fence_gate", 107},  \
	{"brick_stairs", 108},  \
	{"stone_brick_stairs", 109},  \
	{"mycelium", 110},  \
	{"light_gray_concrete", 111},  \
	{"nether_brick", 112},  \
	{"nether_brick_fence", 113},  \
	{"nether_brick_stairs", 114},  \
	{"nether_wart", 115},  \
	{"enchanting_table", 116},  \
	{"brewing_stand", 117},  \
	{"cauldron", 118},  \
	{"end_portal", 119},  \
	{"end_portal_frame", 120},  \
	{"end_stone", 121},  \
	{"dragon_egg", 122},  \
	{"redstone_lamp", 123},  \
	{"shroomlight", 124},  \
	{"oak_wood", 125},  \
	{"oak_slab", 126},  \
	{"cocoa", 127},  \
	{"sandstone_stairs", 128},  \
	{"emerald_ore", 129},  \
	{"ender_chest", 130},  \
	{"tripwire_hook", 131},  \
	{"tripwire", 132},  \
	{"emerald_block", 133},  \
	{"spruce_stairs", 134},  \
	{"birch_stairs", 135},  \
	{"jungle_stairs", 136},  \
	{"command_block", 137},  \
	{"beacon", 138},  \
	{"cobblestone_wall", 139},  \
	{"flower_pot", 140},  \
	{"carrots", 141},  \
	{"potatoes", 142},  \
	{"oak_button", 143},  \
	{"skeleton_wall_skull", 144},  \
	{"anvil", 145},  \
	{"trapped_chest", 146},  \
	{"light_weighted_pressure_plate", 147},  \
	{"heavy_weighted_pressure_plate", 148},  \
	{"comparator", 149},  \
	{"chain", 150},  \
	{"daylight_detector", 151},  \
	{"redstone_block", 152},  \
	{"nether_quartz_ore", 153},  \
	{"hopper", 154},  \
	{"quartz_block", 155},  \
	{"quartz_stairs", 156},  \
	{"activator_rail", 157},  \
	{"dropper", 158},  \
	{"pink_stained_glass", 159},  \
	{"white_stained_glass_pane", 160},  \
	{"dead_brain_coral", 161},  \
	{"acacia_planks", 162},  \
	{"acacia_stairs", 163},  \
	{"dark_oak_stairs", 164},  \
	{"slime_block", 165},  \
	{"barrier", 166},  \
	{"iron_trapdoor", 167},  \
	{"prismarine", 168},  \
	{"sea_lantern", 169},  \
	{"hay_block", 170},  \
	{"white_carpet", 171},  \
	{"coarse_dirt", 172},  \
	{"coal_block", 173},  \
	{"packed_ice", 174},  \
	{"orange_concrete", 175},  \
	{"white_banner", 176},  \
	{"white_wall_banner", 177},  \
	{"white_concrete_powder", 178},  \
	{"red_sandstone", 179},  \
	{"red_sandstone_stairs", 180},  \
	{"red_sandstone_wall", 181},  \
	{"red_sandstone_slab", 182},  \
	{"spruce_fence_gate", 183},  \
	{"birch_fence_gate", 184},  \
	{"jungle_fence_gate", 185},  \
	{"dark_oak_fence_gate", 186},  \
	{"acacia_fence_gate", 187},  \
	{"spruce_fence", 188},  \
	{"birch_fence", 189},  \
	{"jungle_fence", 190},  \
	{"dark_oak_fence", 191},  \
	{"acacia_fence", 192},  \
	{"spruce_door", 193},  \
	{"birch_door", 194},  \
	{"jungle_door", 195},  \
	{"acacia_door", 196},  \
	{"dark_oak_door", 197},  \
	{"end_rod", 198},  \
	{"chorus_plant", 199},  \
	{"chorus_flower", 200},  \
	{"purpur_block", 201},  \
	{"purpur_pillar", 202},  \
	{"purpur_stairs", 203},  \
	{"purple_stained_glass", 204},  \
	{"purpur_slab", 205},  \
	{"end_stone_bricks", 206},  \
	{"beetroots", 207},  \
	{"grass_path", 208},  \
	{"end_gateway", 209},  \
	{"repeating_command_block", 210},  \
	{"chain_command_block", 211},  \
	{"frosted_ice", 212},  \
	{"magma_block", 213},  \
	{"nether_wart_block", 214},  \
	{"red_nether_bricks", 215},  \
	{"bone_block", 216},  \
	{"structure_void", 217},  \
	{"observer", 218},  \
	{"white_shulker_box", 219},  \
	{"orange_shulker_box", 220},  \
	{"magenta_shulker_box", 221},  \
	{"light_blue_shulker_box", 222},  \
	{"yellow_shulker_box", 223},  \
	{"lime_shulker_box", 224},  \
	{"pink_shulker_box", 225},  \
	{"gray_shulker_box", 226},  \
	{"light_gray_shulker_box", 227},  \
	{"cyan_shulker_box", 228},  \
	{"purple_shulker_box", 229},  \
	{"blue_shulker_box", 230},  \
	{"brown_shulker_box", 231},  \
	{"green_shulker_box", 232},  \
	{"red_shulker_box", 233},  \
	{"black_shulker_box", 234},  \
	{"white_glazed_terracotta", 235},  \
	{"orange_glazed_terracotta", 236},  \
	{"magenta_glazed_terracotta", 237},  \
	{"light_blue_glazed_terracotta", 238},  \
	{"yellow_glazed_terracotta", 239},  \
	{"lime_glazed_terracotta", 240},  \
	{"pink_glazed_terracotta", 241},  \
	{"gray_glazed_terracotta", 242},  \
	{"light_gray_glazed_terracotta", 243},  \
	{"cyan_glazed_terracotta", 244},  \
	{"purple_glazed_terracotta", 245},  \
	{"blue_glazed_terracotta", 246},  \
	{"brown_glazed_terracotta", 247},  \
	{"green_glazed_terracotta", 248},  \
	{"red_glazed_terracotta", 249},  \
	{"black_glazed_terracotta", 250},  \
	{"gray_concrete", 251},  \
	{"gray_concrete_powder", 252},  \
	{"deepslate_redstone_ore", 1},\
	{"deepslate_iron_ore", 1},	\
	{"kelp", 2},					\
	{"deepslate", 118},				\
	{"moss_carpet", 1},			\
	{"granite", 1},				\
	{"diorite", 82},				\
	{"glow_lichen", 1},			\
	{"copper_ore", 1},			\
	{"tuff", 1},				\
	{"deepslate_gold_ore", 1},	\
	{"flowering_azalea", 1},	\
	{"azalea", 6},				\
	{"cave_vines", 1},			\
	{"cave_vines_plant", 1},	\
	{"big_dripleaf", 1},		\
	{"big_dripleaf_stem", 1},	\
	{"spore_blossom", 1},		\
	{"deepslate_diamond_ore", 1},	\
	{"budding_amethyst", 1},	\
	{"smooth_basalt", 1},		\
	{"birch_log", 1},			\
	{"cave_air", 1},			\
	{"kelp_plant", 1},			\
	{"deepslate_lapis_ore", 1},	\
	{"deepslate_copper_ore", 1},\
	{"moss_block", 1},			\
	{"small_amethyst_bud", 1},	\
	{"calcite", 1},				\
	{"amethyst_block", 1},		\
	{"medium_amethyst_bud", 1},	\
	{"large_amethyst_bud", 1},	\
	{"amethyst_cluster", 1},	\
	{"mossy_stone_bricks", 1},	\
	{"cracked_stone_bricks", 1},\
	{"small_dripleaf", 1},		\
	{"deepslate_coal_ore", 1},	\
	{"fern", 165},				\
	{"raw_copper_block", 1},	\
	{"raw_iron_block", 1},		\
	{"jungle_log", 1},			\
	{"wall_torch", 1},			\
	{"raw_iron_block", 1},		\
	{"polished_granite", 1},	\
	{"cut_sandstone", 1},		\
	{"oxeye_daisy", 1},			\
	{"sugar_cane", 1},			\
	{"azure_bluet", 1},			\
	{"cornflower", 1},			\
	{"structure_block", 255}	\
}

const PaletteArray &getPaletteArray() {
	static const McColorScheme mccolors[] MCCOLORS;
	static const PaletteArray mcPalette(mccolors, lengthof(mccolors));
	return mcPalette;
}

const PaletteMap &getPaletteMap() {
	// https://github.com/mcedit/mcedit2/tree/master/src/mceditlib/blocktypes
	// https://minecraft.gamepedia.com/Java_Edition_data_values
	// https://minecraft.gamepedia.com/Java_Edition_data_values/Pre-flattening#Block_IDs
	// https://github.com/erich666/Mineways/blob/c84d1dad8ef9c5d59008b3eabff0161aae9600d6/Win/nbt.cpp#L370
	static const PaletteMap mcPalette MCCOLORS;
	return mcPalette;
}

} // namespace voxelformat
