function init()
  chr.setRace("human")
  chr.setGender("male")
  chr.setHead("head/shepherd")
  chr.setBelt("belt/shepherd")
  chr.setChest("chest/shepherd")
  chr.setPants("pants/shepherd")
  chr.setHand("hand/shepherd")
  chr.setFoot("foot/shepherd")
  chr.setShoulder("shoulder/shepherd")
end
