function init()
  chr.setRace("undead")
  chr.setGender("male")
  chr.setHead("heads/default")
  chr.setBelt("belts/default")
  chr.setChest("chests/default")
  chr.setPants("pants/default")
  chr.setHand("hands/default")
  chr.setFoot("feets/default")
  chr.setShoulder("")

  chr.setHeadHeight(14.0)
  chr.setChestHeight(1.0)
  chr.setInvisibleLegHeight(0.4)
  chr.setFootRight(-1.2)
end
