function init()
  chr.setRace("undead")
  chr.setGender("male")
  chr.setHead("heads/skeleton")
  chr.setBelt("belts/skeleton")
  chr.setChest("chests/skeleton")
  chr.setPants("pants/skeleton")
  chr.setHand("hands/skeleton")
  chr.setFoot("feets/skeleton")
  chr.setShoulder("shoulders/skeleton")

  chr.setHandRight(-6.5)
  chr.setShoulderRight(-3.0)
  chr.setShoulderForward(-1.0)
  chr.setChestHeight(5.0)
  chr.setBeltHeight(1.0)
  chr.setInvisibleLegHeight(0.4)
  chr.setFootRight(-3.2)
end
