/* WARNING: This file was automatically generated */
/* Do not edit. */

#include "flextVk.h"
#include <SDL3/SDL.h>

#ifdef __cplusplus
extern "C" {
#endif

PFNVKCREATEDEBUGREPORTCALLBACKEXT_PROC* flextvkCreateDebugReportCallbackEXT = NULL;
PFNVKDEBUGREPORTMESSAGEEXT_PROC* flextvkDebugReportMessageEXT = NULL;
PFNVKDESTROYDEBUGREPORTCALLBACKEXT_PROC* flextvkDestroyDebugReportCallbackEXT = NULL;
PFNVKDESTROYSURFACEKHR_PROC* flextvkDestroySurfaceKHR = NULL;
PFNVKGETPHYSICALDEVICESURFACECAPABILITIESKHR_PROC* flextvkGetPhysicalDeviceSurfaceCapabilitiesKHR = NULL;
PFNVKGETPHYSICALDEVICESURFACEFORMATSKHR_PROC* flextvkGetPhysicalDeviceSurfaceFormatsKHR = NULL;
PFNVKGETPHYSICALDEVICESURFACEPRESENTMODESKHR_PROC* flextvkGetPhysicalDeviceSurfacePresentModesKHR = NULL;
PFNVKGETPHYSICALDEVICESURFACESUPPORTKHR_PROC* flextvkGetPhysicalDeviceSurfaceSupportKHR = NULL;
PFNVKACQUIRENEXTIMAGE2KHR_PROC* flextvkAcquireNextImage2KHR = NULL;
PFNVKACQUIRENEXTIMAGEKHR_PROC* flextvkAcquireNextImageKHR = NULL;
PFNVKCREATESWAPCHAINKHR_PROC* flextvkCreateSwapchainKHR = NULL;
PFNVKDESTROYSWAPCHAINKHR_PROC* flextvkDestroySwapchainKHR = NULL;
PFNVKGETDEVICEGROUPPRESENTCAPABILITIESKHR_PROC* flextvkGetDeviceGroupPresentCapabilitiesKHR = NULL;
PFNVKGETDEVICEGROUPSURFACEPRESENTMODESKHR_PROC* flextvkGetDeviceGroupSurfacePresentModesKHR = NULL;
PFNVKGETPHYSICALDEVICEPRESENTRECTANGLESKHR_PROC* flextvkGetPhysicalDevicePresentRectanglesKHR = NULL;
PFNVKGETSWAPCHAINIMAGESKHR_PROC* flextvkGetSwapchainImagesKHR = NULL;
PFNVKQUEUEPRESENTKHR_PROC* flextvkQueuePresentKHR = NULL;
PFNVKALLOCATECOMMANDBUFFERS_PROC* flextvkAllocateCommandBuffers = NULL;
PFNVKALLOCATEDESCRIPTORSETS_PROC* flextvkAllocateDescriptorSets = NULL;
PFNVKALLOCATEMEMORY_PROC* flextvkAllocateMemory = NULL;
PFNVKBEGINCOMMANDBUFFER_PROC* flextvkBeginCommandBuffer = NULL;
PFNVKBINDBUFFERMEMORY_PROC* flextvkBindBufferMemory = NULL;
PFNVKBINDIMAGEMEMORY_PROC* flextvkBindImageMemory = NULL;
PFNVKCMDBEGINQUERY_PROC* flextvkCmdBeginQuery = NULL;
PFNVKCMDBEGINRENDERPASS_PROC* flextvkCmdBeginRenderPass = NULL;
PFNVKCMDBINDDESCRIPTORSETS_PROC* flextvkCmdBindDescriptorSets = NULL;
PFNVKCMDBINDINDEXBUFFER_PROC* flextvkCmdBindIndexBuffer = NULL;
PFNVKCMDBINDPIPELINE_PROC* flextvkCmdBindPipeline = NULL;
PFNVKCMDBINDVERTEXBUFFERS_PROC* flextvkCmdBindVertexBuffers = NULL;
PFNVKCMDBLITIMAGE_PROC* flextvkCmdBlitImage = NULL;
PFNVKCMDCLEARATTACHMENTS_PROC* flextvkCmdClearAttachments = NULL;
PFNVKCMDCLEARCOLORIMAGE_PROC* flextvkCmdClearColorImage = NULL;
PFNVKCMDCLEARDEPTHSTENCILIMAGE_PROC* flextvkCmdClearDepthStencilImage = NULL;
PFNVKCMDCOPYBUFFER_PROC* flextvkCmdCopyBuffer = NULL;
PFNVKCMDCOPYBUFFERTOIMAGE_PROC* flextvkCmdCopyBufferToImage = NULL;
PFNVKCMDCOPYIMAGE_PROC* flextvkCmdCopyImage = NULL;
PFNVKCMDCOPYIMAGETOBUFFER_PROC* flextvkCmdCopyImageToBuffer = NULL;
PFNVKCMDCOPYQUERYPOOLRESULTS_PROC* flextvkCmdCopyQueryPoolResults = NULL;
PFNVKCMDDISPATCH_PROC* flextvkCmdDispatch = NULL;
PFNVKCMDDISPATCHINDIRECT_PROC* flextvkCmdDispatchIndirect = NULL;
PFNVKCMDDRAW_PROC* flextvkCmdDraw = NULL;
PFNVKCMDDRAWINDEXED_PROC* flextvkCmdDrawIndexed = NULL;
PFNVKCMDDRAWINDEXEDINDIRECT_PROC* flextvkCmdDrawIndexedIndirect = NULL;
PFNVKCMDDRAWINDIRECT_PROC* flextvkCmdDrawIndirect = NULL;
PFNVKCMDENDQUERY_PROC* flextvkCmdEndQuery = NULL;
PFNVKCMDENDRENDERPASS_PROC* flextvkCmdEndRenderPass = NULL;
PFNVKCMDEXECUTECOMMANDS_PROC* flextvkCmdExecuteCommands = NULL;
PFNVKCMDFILLBUFFER_PROC* flextvkCmdFillBuffer = NULL;
PFNVKCMDNEXTSUBPASS_PROC* flextvkCmdNextSubpass = NULL;
PFNVKCMDPIPELINEBARRIER_PROC* flextvkCmdPipelineBarrier = NULL;
PFNVKCMDPUSHCONSTANTS_PROC* flextvkCmdPushConstants = NULL;
PFNVKCMDRESETEVENT_PROC* flextvkCmdResetEvent = NULL;
PFNVKCMDRESETQUERYPOOL_PROC* flextvkCmdResetQueryPool = NULL;
PFNVKCMDRESOLVEIMAGE_PROC* flextvkCmdResolveImage = NULL;
PFNVKCMDSETBLENDCONSTANTS_PROC* flextvkCmdSetBlendConstants = NULL;
PFNVKCMDSETDEPTHBIAS_PROC* flextvkCmdSetDepthBias = NULL;
PFNVKCMDSETDEPTHBOUNDS_PROC* flextvkCmdSetDepthBounds = NULL;
PFNVKCMDSETEVENT_PROC* flextvkCmdSetEvent = NULL;
PFNVKCMDSETLINEWIDTH_PROC* flextvkCmdSetLineWidth = NULL;
PFNVKCMDSETSCISSOR_PROC* flextvkCmdSetScissor = NULL;
PFNVKCMDSETSTENCILCOMPAREMASK_PROC* flextvkCmdSetStencilCompareMask = NULL;
PFNVKCMDSETSTENCILREFERENCE_PROC* flextvkCmdSetStencilReference = NULL;
PFNVKCMDSETSTENCILWRITEMASK_PROC* flextvkCmdSetStencilWriteMask = NULL;
PFNVKCMDSETVIEWPORT_PROC* flextvkCmdSetViewport = NULL;
PFNVKCMDUPDATEBUFFER_PROC* flextvkCmdUpdateBuffer = NULL;
PFNVKCMDWAITEVENTS_PROC* flextvkCmdWaitEvents = NULL;
PFNVKCMDWRITETIMESTAMP_PROC* flextvkCmdWriteTimestamp = NULL;
PFNVKCREATEBUFFER_PROC* flextvkCreateBuffer = NULL;
PFNVKCREATEBUFFERVIEW_PROC* flextvkCreateBufferView = NULL;
PFNVKCREATECOMMANDPOOL_PROC* flextvkCreateCommandPool = NULL;
PFNVKCREATECOMPUTEPIPELINES_PROC* flextvkCreateComputePipelines = NULL;
PFNVKCREATEDESCRIPTORPOOL_PROC* flextvkCreateDescriptorPool = NULL;
PFNVKCREATEDESCRIPTORSETLAYOUT_PROC* flextvkCreateDescriptorSetLayout = NULL;
PFNVKCREATEDEVICE_PROC* flextvkCreateDevice = NULL;
PFNVKCREATEEVENT_PROC* flextvkCreateEvent = NULL;
PFNVKCREATEFENCE_PROC* flextvkCreateFence = NULL;
PFNVKCREATEFRAMEBUFFER_PROC* flextvkCreateFramebuffer = NULL;
PFNVKCREATEGRAPHICSPIPELINES_PROC* flextvkCreateGraphicsPipelines = NULL;
PFNVKCREATEIMAGE_PROC* flextvkCreateImage = NULL;
PFNVKCREATEIMAGEVIEW_PROC* flextvkCreateImageView = NULL;
PFNVKCREATEINSTANCE_PROC* flextvkCreateInstance = NULL;
PFNVKCREATEPIPELINECACHE_PROC* flextvkCreatePipelineCache = NULL;
PFNVKCREATEPIPELINELAYOUT_PROC* flextvkCreatePipelineLayout = NULL;
PFNVKCREATEQUERYPOOL_PROC* flextvkCreateQueryPool = NULL;
PFNVKCREATERENDERPASS_PROC* flextvkCreateRenderPass = NULL;
PFNVKCREATESAMPLER_PROC* flextvkCreateSampler = NULL;
PFNVKCREATESEMAPHORE_PROC* flextvkCreateSemaphore = NULL;
PFNVKCREATESHADERMODULE_PROC* flextvkCreateShaderModule = NULL;
PFNVKDESTROYBUFFER_PROC* flextvkDestroyBuffer = NULL;
PFNVKDESTROYBUFFERVIEW_PROC* flextvkDestroyBufferView = NULL;
PFNVKDESTROYCOMMANDPOOL_PROC* flextvkDestroyCommandPool = NULL;
PFNVKDESTROYDESCRIPTORPOOL_PROC* flextvkDestroyDescriptorPool = NULL;
PFNVKDESTROYDESCRIPTORSETLAYOUT_PROC* flextvkDestroyDescriptorSetLayout = NULL;
PFNVKDESTROYDEVICE_PROC* flextvkDestroyDevice = NULL;
PFNVKDESTROYEVENT_PROC* flextvkDestroyEvent = NULL;
PFNVKDESTROYFENCE_PROC* flextvkDestroyFence = NULL;
PFNVKDESTROYFRAMEBUFFER_PROC* flextvkDestroyFramebuffer = NULL;
PFNVKDESTROYIMAGE_PROC* flextvkDestroyImage = NULL;
PFNVKDESTROYIMAGEVIEW_PROC* flextvkDestroyImageView = NULL;
PFNVKDESTROYINSTANCE_PROC* flextvkDestroyInstance = NULL;
PFNVKDESTROYPIPELINE_PROC* flextvkDestroyPipeline = NULL;
PFNVKDESTROYPIPELINECACHE_PROC* flextvkDestroyPipelineCache = NULL;
PFNVKDESTROYPIPELINELAYOUT_PROC* flextvkDestroyPipelineLayout = NULL;
PFNVKDESTROYQUERYPOOL_PROC* flextvkDestroyQueryPool = NULL;
PFNVKDESTROYRENDERPASS_PROC* flextvkDestroyRenderPass = NULL;
PFNVKDESTROYSAMPLER_PROC* flextvkDestroySampler = NULL;
PFNVKDESTROYSEMAPHORE_PROC* flextvkDestroySemaphore = NULL;
PFNVKDESTROYSHADERMODULE_PROC* flextvkDestroyShaderModule = NULL;
PFNVKDEVICEWAITIDLE_PROC* flextvkDeviceWaitIdle = NULL;
PFNVKENDCOMMANDBUFFER_PROC* flextvkEndCommandBuffer = NULL;
PFNVKENUMERATEDEVICEEXTENSIONPROPERTIES_PROC* flextvkEnumerateDeviceExtensionProperties = NULL;
PFNVKENUMERATEDEVICELAYERPROPERTIES_PROC* flextvkEnumerateDeviceLayerProperties = NULL;
PFNVKENUMERATEINSTANCEEXTENSIONPROPERTIES_PROC* flextvkEnumerateInstanceExtensionProperties = NULL;
PFNVKENUMERATEINSTANCELAYERPROPERTIES_PROC* flextvkEnumerateInstanceLayerProperties = NULL;
PFNVKENUMERATEPHYSICALDEVICES_PROC* flextvkEnumeratePhysicalDevices = NULL;
PFNVKFLUSHMAPPEDMEMORYRANGES_PROC* flextvkFlushMappedMemoryRanges = NULL;
PFNVKFREECOMMANDBUFFERS_PROC* flextvkFreeCommandBuffers = NULL;
PFNVKFREEDESCRIPTORSETS_PROC* flextvkFreeDescriptorSets = NULL;
PFNVKFREEMEMORY_PROC* flextvkFreeMemory = NULL;
PFNVKGETBUFFERMEMORYREQUIREMENTS_PROC* flextvkGetBufferMemoryRequirements = NULL;
PFNVKGETDEVICEMEMORYCOMMITMENT_PROC* flextvkGetDeviceMemoryCommitment = NULL;
PFNVKGETDEVICEPROCADDR_PROC* flextvkGetDeviceProcAddr = NULL;
PFNVKGETDEVICEQUEUE_PROC* flextvkGetDeviceQueue = NULL;
PFNVKGETEVENTSTATUS_PROC* flextvkGetEventStatus = NULL;
PFNVKGETFENCESTATUS_PROC* flextvkGetFenceStatus = NULL;
PFNVKGETIMAGEMEMORYREQUIREMENTS_PROC* flextvkGetImageMemoryRequirements = NULL;
PFNVKGETIMAGESPARSEMEMORYREQUIREMENTS_PROC* flextvkGetImageSparseMemoryRequirements = NULL;
PFNVKGETIMAGESUBRESOURCELAYOUT_PROC* flextvkGetImageSubresourceLayout = NULL;
PFNVKGETINSTANCEPROCADDR_PROC* flextvkGetInstanceProcAddr = NULL;
PFNVKGETPHYSICALDEVICEFEATURES_PROC* flextvkGetPhysicalDeviceFeatures = NULL;
PFNVKGETPHYSICALDEVICEFORMATPROPERTIES_PROC* flextvkGetPhysicalDeviceFormatProperties = NULL;
PFNVKGETPHYSICALDEVICEIMAGEFORMATPROPERTIES_PROC* flextvkGetPhysicalDeviceImageFormatProperties = NULL;
PFNVKGETPHYSICALDEVICEMEMORYPROPERTIES_PROC* flextvkGetPhysicalDeviceMemoryProperties = NULL;
PFNVKGETPHYSICALDEVICEPROPERTIES_PROC* flextvkGetPhysicalDeviceProperties = NULL;
PFNVKGETPHYSICALDEVICEQUEUEFAMILYPROPERTIES_PROC* flextvkGetPhysicalDeviceQueueFamilyProperties = NULL;
PFNVKGETPHYSICALDEVICESPARSEIMAGEFORMATPROPERTIES_PROC* flextvkGetPhysicalDeviceSparseImageFormatProperties = NULL;
PFNVKGETPIPELINECACHEDATA_PROC* flextvkGetPipelineCacheData = NULL;
PFNVKGETQUERYPOOLRESULTS_PROC* flextvkGetQueryPoolResults = NULL;
PFNVKGETRENDERAREAGRANULARITY_PROC* flextvkGetRenderAreaGranularity = NULL;
PFNVKINVALIDATEMAPPEDMEMORYRANGES_PROC* flextvkInvalidateMappedMemoryRanges = NULL;
PFNVKMAPMEMORY_PROC* flextvkMapMemory = NULL;
PFNVKMERGEPIPELINECACHES_PROC* flextvkMergePipelineCaches = NULL;
PFNVKQUEUEBINDSPARSE_PROC* flextvkQueueBindSparse = NULL;
PFNVKQUEUESUBMIT_PROC* flextvkQueueSubmit = NULL;
PFNVKQUEUEWAITIDLE_PROC* flextvkQueueWaitIdle = NULL;
PFNVKRESETCOMMANDBUFFER_PROC* flextvkResetCommandBuffer = NULL;
PFNVKRESETCOMMANDPOOL_PROC* flextvkResetCommandPool = NULL;
PFNVKRESETDESCRIPTORPOOL_PROC* flextvkResetDescriptorPool = NULL;
PFNVKRESETEVENT_PROC* flextvkResetEvent = NULL;
PFNVKRESETFENCES_PROC* flextvkResetFences = NULL;
PFNVKSETEVENT_PROC* flextvkSetEvent = NULL;
PFNVKUNMAPMEMORY_PROC* flextvkUnmapMemory = NULL;
PFNVKUPDATEDESCRIPTORSETS_PROC* flextvkUpdateDescriptorSets = NULL;
PFNVKWAITFORFENCES_PROC* flextvkWaitForFences = NULL;

static void *vulkanLibrary = NULL;

void flextVkShutdown(void) {
    SDL_UnloadObject(vulkanLibrary);
    vulkanLibrary = NULL;
}

int flextVkInit(void) {
#if defined(__linux__)
    vulkanLibrary = SDL_LoadObject("libvulkan.so");
    if (vulkanLibrary == NULL) {
        vulkanLibrary = SDL_LoadObject("libvulkan.so.1");
    }
#elif defined(SDL_PLATFORM_APPLE)
    vulkanLibrary = SDL_LoadObject("libvulkan.dylib");
#elif defined(_WIN32)
    vulkanLibrary = SDL_LoadObject("vulkan-1.dll");
#else
#error unsupported platform
#endif
    if (vulkanLibrary == NULL) {
        return SDL_SetError("Could not load the vulkan library");
    }
    flextvkCreateInstance = (PFNVKCREATEINSTANCE_PROC*)SDL_LoadFunction(vulkanLibrary, "vkCreateInstance");
    flextvkEnumerateInstanceExtensionProperties = (PFNVKENUMERATEINSTANCEEXTENSIONPROPERTIES_PROC*)SDL_LoadFunction(vulkanLibrary, "vkEnumerateInstanceExtensionProperties");
    flextvkEnumerateInstanceLayerProperties = (PFNVKENUMERATEINSTANCELAYERPROPERTIES_PROC*)SDL_LoadFunction(vulkanLibrary, "vkEnumerateInstanceLayerProperties");
    flextvkGetInstanceProcAddr = (PFNVKGETINSTANCEPROCADDR_PROC*)SDL_LoadFunction(vulkanLibrary, "vkGetInstanceProcAddr");
    return 0;
}

void flextVkInitInstance(VkInstance instance) {
    flextvkCreateDebugReportCallbackEXT = (PFNVKCREATEDEBUGREPORTCALLBACKEXT_PROC*)flextvkGetInstanceProcAddr(instance, "vkCreateDebugReportCallbackEXT");
    flextvkDebugReportMessageEXT = (PFNVKDEBUGREPORTMESSAGEEXT_PROC*)flextvkGetInstanceProcAddr(instance, "vkDebugReportMessageEXT");
    flextvkDestroyDebugReportCallbackEXT = (PFNVKDESTROYDEBUGREPORTCALLBACKEXT_PROC*)flextvkGetInstanceProcAddr(instance, "vkDestroyDebugReportCallbackEXT");
    flextvkDestroySurfaceKHR = (PFNVKDESTROYSURFACEKHR_PROC*)flextvkGetInstanceProcAddr(instance, "vkDestroySurfaceKHR");
    flextvkGetPhysicalDeviceSurfaceCapabilitiesKHR = (PFNVKGETPHYSICALDEVICESURFACECAPABILITIESKHR_PROC*)flextvkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceSurfaceCapabilitiesKHR");
    flextvkGetPhysicalDeviceSurfaceFormatsKHR = (PFNVKGETPHYSICALDEVICESURFACEFORMATSKHR_PROC*)flextvkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceSurfaceFormatsKHR");
    flextvkGetPhysicalDeviceSurfacePresentModesKHR = (PFNVKGETPHYSICALDEVICESURFACEPRESENTMODESKHR_PROC*)flextvkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceSurfacePresentModesKHR");
    flextvkGetPhysicalDeviceSurfaceSupportKHR = (PFNVKGETPHYSICALDEVICESURFACESUPPORTKHR_PROC*)flextvkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceSurfaceSupportKHR");
    flextvkAcquireNextImage2KHR = (PFNVKACQUIRENEXTIMAGE2KHR_PROC*)flextvkGetInstanceProcAddr(instance, "vkAcquireNextImage2KHR");
    flextvkAcquireNextImageKHR = (PFNVKACQUIRENEXTIMAGEKHR_PROC*)flextvkGetInstanceProcAddr(instance, "vkAcquireNextImageKHR");
    flextvkCreateSwapchainKHR = (PFNVKCREATESWAPCHAINKHR_PROC*)flextvkGetInstanceProcAddr(instance, "vkCreateSwapchainKHR");
    flextvkDestroySwapchainKHR = (PFNVKDESTROYSWAPCHAINKHR_PROC*)flextvkGetInstanceProcAddr(instance, "vkDestroySwapchainKHR");
    flextvkGetDeviceGroupPresentCapabilitiesKHR = (PFNVKGETDEVICEGROUPPRESENTCAPABILITIESKHR_PROC*)flextvkGetInstanceProcAddr(instance, "vkGetDeviceGroupPresentCapabilitiesKHR");
    flextvkGetDeviceGroupSurfacePresentModesKHR = (PFNVKGETDEVICEGROUPSURFACEPRESENTMODESKHR_PROC*)flextvkGetInstanceProcAddr(instance, "vkGetDeviceGroupSurfacePresentModesKHR");
    flextvkGetPhysicalDevicePresentRectanglesKHR = (PFNVKGETPHYSICALDEVICEPRESENTRECTANGLESKHR_PROC*)flextvkGetInstanceProcAddr(instance, "vkGetPhysicalDevicePresentRectanglesKHR");
    flextvkGetSwapchainImagesKHR = (PFNVKGETSWAPCHAINIMAGESKHR_PROC*)flextvkGetInstanceProcAddr(instance, "vkGetSwapchainImagesKHR");
    flextvkQueuePresentKHR = (PFNVKQUEUEPRESENTKHR_PROC*)flextvkGetInstanceProcAddr(instance, "vkQueuePresentKHR");
    flextvkAllocateCommandBuffers = (PFNVKALLOCATECOMMANDBUFFERS_PROC*)flextvkGetInstanceProcAddr(instance, "vkAllocateCommandBuffers");
    flextvkAllocateDescriptorSets = (PFNVKALLOCATEDESCRIPTORSETS_PROC*)flextvkGetInstanceProcAddr(instance, "vkAllocateDescriptorSets");
    flextvkAllocateMemory = (PFNVKALLOCATEMEMORY_PROC*)flextvkGetInstanceProcAddr(instance, "vkAllocateMemory");
    flextvkBeginCommandBuffer = (PFNVKBEGINCOMMANDBUFFER_PROC*)flextvkGetInstanceProcAddr(instance, "vkBeginCommandBuffer");
    flextvkBindBufferMemory = (PFNVKBINDBUFFERMEMORY_PROC*)flextvkGetInstanceProcAddr(instance, "vkBindBufferMemory");
    flextvkBindImageMemory = (PFNVKBINDIMAGEMEMORY_PROC*)flextvkGetInstanceProcAddr(instance, "vkBindImageMemory");
    flextvkCmdBeginQuery = (PFNVKCMDBEGINQUERY_PROC*)flextvkGetInstanceProcAddr(instance, "vkCmdBeginQuery");
    flextvkCmdBeginRenderPass = (PFNVKCMDBEGINRENDERPASS_PROC*)flextvkGetInstanceProcAddr(instance, "vkCmdBeginRenderPass");
    flextvkCmdBindDescriptorSets = (PFNVKCMDBINDDESCRIPTORSETS_PROC*)flextvkGetInstanceProcAddr(instance, "vkCmdBindDescriptorSets");
    flextvkCmdBindIndexBuffer = (PFNVKCMDBINDINDEXBUFFER_PROC*)flextvkGetInstanceProcAddr(instance, "vkCmdBindIndexBuffer");
    flextvkCmdBindPipeline = (PFNVKCMDBINDPIPELINE_PROC*)flextvkGetInstanceProcAddr(instance, "vkCmdBindPipeline");
    flextvkCmdBindVertexBuffers = (PFNVKCMDBINDVERTEXBUFFERS_PROC*)flextvkGetInstanceProcAddr(instance, "vkCmdBindVertexBuffers");
    flextvkCmdBlitImage = (PFNVKCMDBLITIMAGE_PROC*)flextvkGetInstanceProcAddr(instance, "vkCmdBlitImage");
    flextvkCmdClearAttachments = (PFNVKCMDCLEARATTACHMENTS_PROC*)flextvkGetInstanceProcAddr(instance, "vkCmdClearAttachments");
    flextvkCmdClearColorImage = (PFNVKCMDCLEARCOLORIMAGE_PROC*)flextvkGetInstanceProcAddr(instance, "vkCmdClearColorImage");
    flextvkCmdClearDepthStencilImage = (PFNVKCMDCLEARDEPTHSTENCILIMAGE_PROC*)flextvkGetInstanceProcAddr(instance, "vkCmdClearDepthStencilImage");
    flextvkCmdCopyBuffer = (PFNVKCMDCOPYBUFFER_PROC*)flextvkGetInstanceProcAddr(instance, "vkCmdCopyBuffer");
    flextvkCmdCopyBufferToImage = (PFNVKCMDCOPYBUFFERTOIMAGE_PROC*)flextvkGetInstanceProcAddr(instance, "vkCmdCopyBufferToImage");
    flextvkCmdCopyImage = (PFNVKCMDCOPYIMAGE_PROC*)flextvkGetInstanceProcAddr(instance, "vkCmdCopyImage");
    flextvkCmdCopyImageToBuffer = (PFNVKCMDCOPYIMAGETOBUFFER_PROC*)flextvkGetInstanceProcAddr(instance, "vkCmdCopyImageToBuffer");
    flextvkCmdCopyQueryPoolResults = (PFNVKCMDCOPYQUERYPOOLRESULTS_PROC*)flextvkGetInstanceProcAddr(instance, "vkCmdCopyQueryPoolResults");
    flextvkCmdDispatch = (PFNVKCMDDISPATCH_PROC*)flextvkGetInstanceProcAddr(instance, "vkCmdDispatch");
    flextvkCmdDispatchIndirect = (PFNVKCMDDISPATCHINDIRECT_PROC*)flextvkGetInstanceProcAddr(instance, "vkCmdDispatchIndirect");
    flextvkCmdDraw = (PFNVKCMDDRAW_PROC*)flextvkGetInstanceProcAddr(instance, "vkCmdDraw");
    flextvkCmdDrawIndexed = (PFNVKCMDDRAWINDEXED_PROC*)flextvkGetInstanceProcAddr(instance, "vkCmdDrawIndexed");
    flextvkCmdDrawIndexedIndirect = (PFNVKCMDDRAWINDEXEDINDIRECT_PROC*)flextvkGetInstanceProcAddr(instance, "vkCmdDrawIndexedIndirect");
    flextvkCmdDrawIndirect = (PFNVKCMDDRAWINDIRECT_PROC*)flextvkGetInstanceProcAddr(instance, "vkCmdDrawIndirect");
    flextvkCmdEndQuery = (PFNVKCMDENDQUERY_PROC*)flextvkGetInstanceProcAddr(instance, "vkCmdEndQuery");
    flextvkCmdEndRenderPass = (PFNVKCMDENDRENDERPASS_PROC*)flextvkGetInstanceProcAddr(instance, "vkCmdEndRenderPass");
    flextvkCmdExecuteCommands = (PFNVKCMDEXECUTECOMMANDS_PROC*)flextvkGetInstanceProcAddr(instance, "vkCmdExecuteCommands");
    flextvkCmdFillBuffer = (PFNVKCMDFILLBUFFER_PROC*)flextvkGetInstanceProcAddr(instance, "vkCmdFillBuffer");
    flextvkCmdNextSubpass = (PFNVKCMDNEXTSUBPASS_PROC*)flextvkGetInstanceProcAddr(instance, "vkCmdNextSubpass");
    flextvkCmdPipelineBarrier = (PFNVKCMDPIPELINEBARRIER_PROC*)flextvkGetInstanceProcAddr(instance, "vkCmdPipelineBarrier");
    flextvkCmdPushConstants = (PFNVKCMDPUSHCONSTANTS_PROC*)flextvkGetInstanceProcAddr(instance, "vkCmdPushConstants");
    flextvkCmdResetEvent = (PFNVKCMDRESETEVENT_PROC*)flextvkGetInstanceProcAddr(instance, "vkCmdResetEvent");
    flextvkCmdResetQueryPool = (PFNVKCMDRESETQUERYPOOL_PROC*)flextvkGetInstanceProcAddr(instance, "vkCmdResetQueryPool");
    flextvkCmdResolveImage = (PFNVKCMDRESOLVEIMAGE_PROC*)flextvkGetInstanceProcAddr(instance, "vkCmdResolveImage");
    flextvkCmdSetBlendConstants = (PFNVKCMDSETBLENDCONSTANTS_PROC*)flextvkGetInstanceProcAddr(instance, "vkCmdSetBlendConstants");
    flextvkCmdSetDepthBias = (PFNVKCMDSETDEPTHBIAS_PROC*)flextvkGetInstanceProcAddr(instance, "vkCmdSetDepthBias");
    flextvkCmdSetDepthBounds = (PFNVKCMDSETDEPTHBOUNDS_PROC*)flextvkGetInstanceProcAddr(instance, "vkCmdSetDepthBounds");
    flextvkCmdSetEvent = (PFNVKCMDSETEVENT_PROC*)flextvkGetInstanceProcAddr(instance, "vkCmdSetEvent");
    flextvkCmdSetLineWidth = (PFNVKCMDSETLINEWIDTH_PROC*)flextvkGetInstanceProcAddr(instance, "vkCmdSetLineWidth");
    flextvkCmdSetScissor = (PFNVKCMDSETSCISSOR_PROC*)flextvkGetInstanceProcAddr(instance, "vkCmdSetScissor");
    flextvkCmdSetStencilCompareMask = (PFNVKCMDSETSTENCILCOMPAREMASK_PROC*)flextvkGetInstanceProcAddr(instance, "vkCmdSetStencilCompareMask");
    flextvkCmdSetStencilReference = (PFNVKCMDSETSTENCILREFERENCE_PROC*)flextvkGetInstanceProcAddr(instance, "vkCmdSetStencilReference");
    flextvkCmdSetStencilWriteMask = (PFNVKCMDSETSTENCILWRITEMASK_PROC*)flextvkGetInstanceProcAddr(instance, "vkCmdSetStencilWriteMask");
    flextvkCmdSetViewport = (PFNVKCMDSETVIEWPORT_PROC*)flextvkGetInstanceProcAddr(instance, "vkCmdSetViewport");
    flextvkCmdUpdateBuffer = (PFNVKCMDUPDATEBUFFER_PROC*)flextvkGetInstanceProcAddr(instance, "vkCmdUpdateBuffer");
    flextvkCmdWaitEvents = (PFNVKCMDWAITEVENTS_PROC*)flextvkGetInstanceProcAddr(instance, "vkCmdWaitEvents");
    flextvkCmdWriteTimestamp = (PFNVKCMDWRITETIMESTAMP_PROC*)flextvkGetInstanceProcAddr(instance, "vkCmdWriteTimestamp");
    flextvkCreateBuffer = (PFNVKCREATEBUFFER_PROC*)flextvkGetInstanceProcAddr(instance, "vkCreateBuffer");
    flextvkCreateBufferView = (PFNVKCREATEBUFFERVIEW_PROC*)flextvkGetInstanceProcAddr(instance, "vkCreateBufferView");
    flextvkCreateCommandPool = (PFNVKCREATECOMMANDPOOL_PROC*)flextvkGetInstanceProcAddr(instance, "vkCreateCommandPool");
    flextvkCreateComputePipelines = (PFNVKCREATECOMPUTEPIPELINES_PROC*)flextvkGetInstanceProcAddr(instance, "vkCreateComputePipelines");
    flextvkCreateDescriptorPool = (PFNVKCREATEDESCRIPTORPOOL_PROC*)flextvkGetInstanceProcAddr(instance, "vkCreateDescriptorPool");
    flextvkCreateDescriptorSetLayout = (PFNVKCREATEDESCRIPTORSETLAYOUT_PROC*)flextvkGetInstanceProcAddr(instance, "vkCreateDescriptorSetLayout");
    flextvkCreateDevice = (PFNVKCREATEDEVICE_PROC*)flextvkGetInstanceProcAddr(instance, "vkCreateDevice");
    flextvkCreateEvent = (PFNVKCREATEEVENT_PROC*)flextvkGetInstanceProcAddr(instance, "vkCreateEvent");
    flextvkCreateFence = (PFNVKCREATEFENCE_PROC*)flextvkGetInstanceProcAddr(instance, "vkCreateFence");
    flextvkCreateFramebuffer = (PFNVKCREATEFRAMEBUFFER_PROC*)flextvkGetInstanceProcAddr(instance, "vkCreateFramebuffer");
    flextvkCreateGraphicsPipelines = (PFNVKCREATEGRAPHICSPIPELINES_PROC*)flextvkGetInstanceProcAddr(instance, "vkCreateGraphicsPipelines");
    flextvkCreateImage = (PFNVKCREATEIMAGE_PROC*)flextvkGetInstanceProcAddr(instance, "vkCreateImage");
    flextvkCreateImageView = (PFNVKCREATEIMAGEVIEW_PROC*)flextvkGetInstanceProcAddr(instance, "vkCreateImageView");
    flextvkCreatePipelineCache = (PFNVKCREATEPIPELINECACHE_PROC*)flextvkGetInstanceProcAddr(instance, "vkCreatePipelineCache");
    flextvkCreatePipelineLayout = (PFNVKCREATEPIPELINELAYOUT_PROC*)flextvkGetInstanceProcAddr(instance, "vkCreatePipelineLayout");
    flextvkCreateQueryPool = (PFNVKCREATEQUERYPOOL_PROC*)flextvkGetInstanceProcAddr(instance, "vkCreateQueryPool");
    flextvkCreateRenderPass = (PFNVKCREATERENDERPASS_PROC*)flextvkGetInstanceProcAddr(instance, "vkCreateRenderPass");
    flextvkCreateSampler = (PFNVKCREATESAMPLER_PROC*)flextvkGetInstanceProcAddr(instance, "vkCreateSampler");
    flextvkCreateSemaphore = (PFNVKCREATESEMAPHORE_PROC*)flextvkGetInstanceProcAddr(instance, "vkCreateSemaphore");
    flextvkCreateShaderModule = (PFNVKCREATESHADERMODULE_PROC*)flextvkGetInstanceProcAddr(instance, "vkCreateShaderModule");
    flextvkDestroyBuffer = (PFNVKDESTROYBUFFER_PROC*)flextvkGetInstanceProcAddr(instance, "vkDestroyBuffer");
    flextvkDestroyBufferView = (PFNVKDESTROYBUFFERVIEW_PROC*)flextvkGetInstanceProcAddr(instance, "vkDestroyBufferView");
    flextvkDestroyCommandPool = (PFNVKDESTROYCOMMANDPOOL_PROC*)flextvkGetInstanceProcAddr(instance, "vkDestroyCommandPool");
    flextvkDestroyDescriptorPool = (PFNVKDESTROYDESCRIPTORPOOL_PROC*)flextvkGetInstanceProcAddr(instance, "vkDestroyDescriptorPool");
    flextvkDestroyDescriptorSetLayout = (PFNVKDESTROYDESCRIPTORSETLAYOUT_PROC*)flextvkGetInstanceProcAddr(instance, "vkDestroyDescriptorSetLayout");
    flextvkDestroyDevice = (PFNVKDESTROYDEVICE_PROC*)flextvkGetInstanceProcAddr(instance, "vkDestroyDevice");
    flextvkDestroyEvent = (PFNVKDESTROYEVENT_PROC*)flextvkGetInstanceProcAddr(instance, "vkDestroyEvent");
    flextvkDestroyFence = (PFNVKDESTROYFENCE_PROC*)flextvkGetInstanceProcAddr(instance, "vkDestroyFence");
    flextvkDestroyFramebuffer = (PFNVKDESTROYFRAMEBUFFER_PROC*)flextvkGetInstanceProcAddr(instance, "vkDestroyFramebuffer");
    flextvkDestroyImage = (PFNVKDESTROYIMAGE_PROC*)flextvkGetInstanceProcAddr(instance, "vkDestroyImage");
    flextvkDestroyImageView = (PFNVKDESTROYIMAGEVIEW_PROC*)flextvkGetInstanceProcAddr(instance, "vkDestroyImageView");
    flextvkDestroyInstance = (PFNVKDESTROYINSTANCE_PROC*)flextvkGetInstanceProcAddr(instance, "vkDestroyInstance");
    flextvkDestroyPipeline = (PFNVKDESTROYPIPELINE_PROC*)flextvkGetInstanceProcAddr(instance, "vkDestroyPipeline");
    flextvkDestroyPipelineCache = (PFNVKDESTROYPIPELINECACHE_PROC*)flextvkGetInstanceProcAddr(instance, "vkDestroyPipelineCache");
    flextvkDestroyPipelineLayout = (PFNVKDESTROYPIPELINELAYOUT_PROC*)flextvkGetInstanceProcAddr(instance, "vkDestroyPipelineLayout");
    flextvkDestroyQueryPool = (PFNVKDESTROYQUERYPOOL_PROC*)flextvkGetInstanceProcAddr(instance, "vkDestroyQueryPool");
    flextvkDestroyRenderPass = (PFNVKDESTROYRENDERPASS_PROC*)flextvkGetInstanceProcAddr(instance, "vkDestroyRenderPass");
    flextvkDestroySampler = (PFNVKDESTROYSAMPLER_PROC*)flextvkGetInstanceProcAddr(instance, "vkDestroySampler");
    flextvkDestroySemaphore = (PFNVKDESTROYSEMAPHORE_PROC*)flextvkGetInstanceProcAddr(instance, "vkDestroySemaphore");
    flextvkDestroyShaderModule = (PFNVKDESTROYSHADERMODULE_PROC*)flextvkGetInstanceProcAddr(instance, "vkDestroyShaderModule");
    flextvkDeviceWaitIdle = (PFNVKDEVICEWAITIDLE_PROC*)flextvkGetInstanceProcAddr(instance, "vkDeviceWaitIdle");
    flextvkEndCommandBuffer = (PFNVKENDCOMMANDBUFFER_PROC*)flextvkGetInstanceProcAddr(instance, "vkEndCommandBuffer");
    flextvkEnumerateDeviceExtensionProperties = (PFNVKENUMERATEDEVICEEXTENSIONPROPERTIES_PROC*)flextvkGetInstanceProcAddr(instance, "vkEnumerateDeviceExtensionProperties");
    flextvkEnumerateDeviceLayerProperties = (PFNVKENUMERATEDEVICELAYERPROPERTIES_PROC*)flextvkGetInstanceProcAddr(instance, "vkEnumerateDeviceLayerProperties");
    flextvkEnumeratePhysicalDevices = (PFNVKENUMERATEPHYSICALDEVICES_PROC*)flextvkGetInstanceProcAddr(instance, "vkEnumeratePhysicalDevices");
    flextvkFlushMappedMemoryRanges = (PFNVKFLUSHMAPPEDMEMORYRANGES_PROC*)flextvkGetInstanceProcAddr(instance, "vkFlushMappedMemoryRanges");
    flextvkFreeCommandBuffers = (PFNVKFREECOMMANDBUFFERS_PROC*)flextvkGetInstanceProcAddr(instance, "vkFreeCommandBuffers");
    flextvkFreeDescriptorSets = (PFNVKFREEDESCRIPTORSETS_PROC*)flextvkGetInstanceProcAddr(instance, "vkFreeDescriptorSets");
    flextvkFreeMemory = (PFNVKFREEMEMORY_PROC*)flextvkGetInstanceProcAddr(instance, "vkFreeMemory");
    flextvkGetBufferMemoryRequirements = (PFNVKGETBUFFERMEMORYREQUIREMENTS_PROC*)flextvkGetInstanceProcAddr(instance, "vkGetBufferMemoryRequirements");
    flextvkGetDeviceMemoryCommitment = (PFNVKGETDEVICEMEMORYCOMMITMENT_PROC*)flextvkGetInstanceProcAddr(instance, "vkGetDeviceMemoryCommitment");
    flextvkGetDeviceProcAddr = (PFNVKGETDEVICEPROCADDR_PROC*)flextvkGetInstanceProcAddr(instance, "vkGetDeviceProcAddr");
    flextvkGetDeviceQueue = (PFNVKGETDEVICEQUEUE_PROC*)flextvkGetInstanceProcAddr(instance, "vkGetDeviceQueue");
    flextvkGetEventStatus = (PFNVKGETEVENTSTATUS_PROC*)flextvkGetInstanceProcAddr(instance, "vkGetEventStatus");
    flextvkGetFenceStatus = (PFNVKGETFENCESTATUS_PROC*)flextvkGetInstanceProcAddr(instance, "vkGetFenceStatus");
    flextvkGetImageMemoryRequirements = (PFNVKGETIMAGEMEMORYREQUIREMENTS_PROC*)flextvkGetInstanceProcAddr(instance, "vkGetImageMemoryRequirements");
    flextvkGetImageSparseMemoryRequirements = (PFNVKGETIMAGESPARSEMEMORYREQUIREMENTS_PROC*)flextvkGetInstanceProcAddr(instance, "vkGetImageSparseMemoryRequirements");
    flextvkGetImageSubresourceLayout = (PFNVKGETIMAGESUBRESOURCELAYOUT_PROC*)flextvkGetInstanceProcAddr(instance, "vkGetImageSubresourceLayout");
    flextvkGetPhysicalDeviceFeatures = (PFNVKGETPHYSICALDEVICEFEATURES_PROC*)flextvkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceFeatures");
    flextvkGetPhysicalDeviceFormatProperties = (PFNVKGETPHYSICALDEVICEFORMATPROPERTIES_PROC*)flextvkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceFormatProperties");
    flextvkGetPhysicalDeviceImageFormatProperties = (PFNVKGETPHYSICALDEVICEIMAGEFORMATPROPERTIES_PROC*)flextvkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceImageFormatProperties");
    flextvkGetPhysicalDeviceMemoryProperties = (PFNVKGETPHYSICALDEVICEMEMORYPROPERTIES_PROC*)flextvkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceMemoryProperties");
    flextvkGetPhysicalDeviceProperties = (PFNVKGETPHYSICALDEVICEPROPERTIES_PROC*)flextvkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceProperties");
    flextvkGetPhysicalDeviceQueueFamilyProperties = (PFNVKGETPHYSICALDEVICEQUEUEFAMILYPROPERTIES_PROC*)flextvkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceQueueFamilyProperties");
    flextvkGetPhysicalDeviceSparseImageFormatProperties = (PFNVKGETPHYSICALDEVICESPARSEIMAGEFORMATPROPERTIES_PROC*)flextvkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceSparseImageFormatProperties");
    flextvkGetPipelineCacheData = (PFNVKGETPIPELINECACHEDATA_PROC*)flextvkGetInstanceProcAddr(instance, "vkGetPipelineCacheData");
    flextvkGetQueryPoolResults = (PFNVKGETQUERYPOOLRESULTS_PROC*)flextvkGetInstanceProcAddr(instance, "vkGetQueryPoolResults");
    flextvkGetRenderAreaGranularity = (PFNVKGETRENDERAREAGRANULARITY_PROC*)flextvkGetInstanceProcAddr(instance, "vkGetRenderAreaGranularity");
    flextvkInvalidateMappedMemoryRanges = (PFNVKINVALIDATEMAPPEDMEMORYRANGES_PROC*)flextvkGetInstanceProcAddr(instance, "vkInvalidateMappedMemoryRanges");
    flextvkMapMemory = (PFNVKMAPMEMORY_PROC*)flextvkGetInstanceProcAddr(instance, "vkMapMemory");
    flextvkMergePipelineCaches = (PFNVKMERGEPIPELINECACHES_PROC*)flextvkGetInstanceProcAddr(instance, "vkMergePipelineCaches");
    flextvkQueueBindSparse = (PFNVKQUEUEBINDSPARSE_PROC*)flextvkGetInstanceProcAddr(instance, "vkQueueBindSparse");
    flextvkQueueSubmit = (PFNVKQUEUESUBMIT_PROC*)flextvkGetInstanceProcAddr(instance, "vkQueueSubmit");
    flextvkQueueWaitIdle = (PFNVKQUEUEWAITIDLE_PROC*)flextvkGetInstanceProcAddr(instance, "vkQueueWaitIdle");
    flextvkResetCommandBuffer = (PFNVKRESETCOMMANDBUFFER_PROC*)flextvkGetInstanceProcAddr(instance, "vkResetCommandBuffer");
    flextvkResetCommandPool = (PFNVKRESETCOMMANDPOOL_PROC*)flextvkGetInstanceProcAddr(instance, "vkResetCommandPool");
    flextvkResetDescriptorPool = (PFNVKRESETDESCRIPTORPOOL_PROC*)flextvkGetInstanceProcAddr(instance, "vkResetDescriptorPool");
    flextvkResetEvent = (PFNVKRESETEVENT_PROC*)flextvkGetInstanceProcAddr(instance, "vkResetEvent");
    flextvkResetFences = (PFNVKRESETFENCES_PROC*)flextvkGetInstanceProcAddr(instance, "vkResetFences");
    flextvkSetEvent = (PFNVKSETEVENT_PROC*)flextvkGetInstanceProcAddr(instance, "vkSetEvent");
    flextvkUnmapMemory = (PFNVKUNMAPMEMORY_PROC*)flextvkGetInstanceProcAddr(instance, "vkUnmapMemory");
    flextvkUpdateDescriptorSets = (PFNVKUPDATEDESCRIPTORSETS_PROC*)flextvkGetInstanceProcAddr(instance, "vkUpdateDescriptorSets");
    flextvkWaitForFences = (PFNVKWAITFORFENCES_PROC*)flextvkGetInstanceProcAddr(instance, "vkWaitForFences");
}

#ifdef __cplusplus
}
#endif
