#--preload-file embed.vengi
#-sSAFE_HEAP=1
#-closure=1
find_package(Threads)
set(EMSCRIPTEN_EXPORTED_FUNCTIONS "_main,_malloc,_free")
set(EMSCRIPTEN_RUNTIME_METHODS "ccall,FS,callMain")
set(CMAKE_EXE_LINKER_FLAGS_DEBUG "${CMAKE_EXE_LINKER_FLAGS_DEBUG} -g -sASSERTIONS=1 -sSAFE_HEAP=1 -sSAFE_HEAP_LOG=1")
set(CMAKE_EXE_LINKER_FLAGS_RELEASE "${CMAKE_EXE_LINKER_FLAGS_RELEASE} -sASSERTIONS=0")
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -sSTACK_SIZE=1048576 -sFETCH=1 -sFULL_ES3=1 -sUSE_PTHREADS=1 -sPTHREAD_POOL_SIZE=4 -sWASM=1 -sUSE_SDL=2 -sINITIAL_MEMORY=384mb -sMAXIMUM_MEMORY=4gb -sALLOW_MEMORY_GROWTH=1 -sEXPORTED_FUNCTIONS=[${EMSCRIPTEN_EXPORTED_FUNCTIONS}] -sEXPORTED_RUNTIME_METHODS=[${EMSCRIPTEN_RUNTIME_METHODS}] -sENVIRONMENT=web,worker -lidbfs.js")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -pthread -Os -sUSE_SDL=2")
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -pthread -Os -sUSE_SDL=2")
