/**
 * @file
 */

#include "voxel/MeshState.h"
#include "app/tests/AbstractTest.h"
#include "core/StringUtil.h"
#include "palette/Palette.h"
#include "voxel/MaterialColor.h"
#include "voxel/SurfaceExtractor.h"

namespace voxel {

class MeshStateTest : public app::AbstractTest {
private:
	using Super = app::AbstractTest;

protected:
	void SetUp() override {
		Super::SetUp();
		const core::VarDef voxelMeshSize(cfg::VoxelMeshSize, 16, "", "", core::CV_READONLY);
		core::Var::registerVar(voxelMeshSize);
		const core::VarDef voxRenderMeshMode(cfg::VoxelMeshMode, (int)voxel::SurfaceExtractionType::Binary, "", "");
		core::Var::registerVar(voxRenderMeshMode);
	}
};

TEST_F(MeshStateTest, testExtractRegion) {
	voxel::RawVolume v(voxel::Region(-1, 1));

	MeshState meshState;
	meshState.construct();
	meshState.init();
	bool deleted = false;
	palette::Palette pal;
	pal.nippon();
	(void)meshState.setVolume(0, &v, &pal, nullptr, true, deleted);

	EXPECT_EQ(0, meshState.pendingExtractions());
	const voxel::Region region(1, 0, 1, 1, 0, 1);
	meshState.scheduleRegionExtraction(0, region);
	// With floor division, the meshSizeMinusOne subtraction correctly maps
	// negative coordinates to the previous chunk, scheduling more chunks.
	// The completeRegion intersection check filters out non-overlapping ones,
	// but for a small volume like [-1,1]^3 most chunks still intersect.
	EXPECT_LT(0, meshState.pendingExtractions());

	(void)meshState.shutdown();
}

TEST_F(MeshStateTest, testExtractRegionBoundary) {
	voxel::RawVolume v(voxel::Region(0, 31));

	MeshState meshState;
	meshState.construct();
	meshState.init();
	bool deleted = false;
	palette::Palette pal;
	pal.nippon();
	(void)meshState.setVolume(0, &v, &pal, nullptr, true, deleted);

	EXPECT_EQ(0, meshState.pendingExtractions());
	// worst case scenario - touching all adjacent regions
	const voxel::Region region(15, 15);
	meshState.scheduleRegionExtraction(0, region);
	EXPECT_EQ(8, meshState.pendingExtractions());

	const voxel::Region region2(14, 14);
	meshState.scheduleRegionExtraction(0, region2);
	EXPECT_EQ(9, meshState.pendingExtractions());
	(void)meshState.shutdown();
}

TEST_F(MeshStateTest, testSetStateBeforeVolume) {
	// Verify that property setters work for indices beyond current size.
	// This simulates the prepareModelNodes flow where updateNodeState
	// calls hide()/gray()/etc. before setVolume is called.
	MeshState meshState;
	meshState.construct();
	meshState.init();

	const int idx = 5;
	// These must grow the internal arrays and store the state
	meshState.hide(idx, false);
	EXPECT_FALSE(meshState.hidden(idx));

	meshState.gray(idx, true);
	EXPECT_TRUE(meshState.grayed(idx));

	meshState.setLocked(idx, true);
	EXPECT_TRUE(meshState.locked(idx));

	// After state setup, setVolume should work normally
	voxel::RawVolume v(voxel::Region(-1, 1));
	palette::Palette pal;
	pal.nippon();
	bool deleted = false;
	(void)meshState.setVolume(idx, &v, &pal, nullptr, true, deleted);
	EXPECT_NE(nullptr, meshState.volume(idx));

	meshState.scheduleRegionExtraction(idx, v.region());
	EXPECT_LT(0, meshState.pendingExtractions());

	(void)meshState.shutdown();
}

// https://github.com/vengi-voxel/vengi/issues/844
// Verify that the cubic extractor via MeshState produces all 6 faces for a
// voxel at the upper edge. MeshState schedules the adjacent chunk via
// completeRegion.shiftUpperCorner(1,1,1) so the positive-direction faces
// are generated by that adjacent chunk.
TEST_F(MeshStateTest, testCubicBoundaryFaceGeneration) {
	voxel::RawVolume v(voxel::Region(0, 15));
	v.setVoxel(15, 15, 15, voxel::createVoxel(voxel::VoxelType::Generic, 1));

	MeshState meshState;
	meshState.construct();
	core::Var::getVar(cfg::VoxelMeshMode)->setVal((int)voxel::SurfaceExtractionType::Cubic);
	meshState.init();
	bool deleted = false;
	palette::Palette pal;
	pal.nippon();
	(void)meshState.setVolume(0, &v, &pal, nullptr, true, deleted);

	meshState.scheduleRegionExtraction(0, v.region());
	// The completeRegion is [0,0,0]-[16,16,16] (shifted +1).
	// This should schedule chunk [0..15] AND the adjacent chunk [16..31]
	// (which intersects completeRegion at 16).
	EXPECT_GE(meshState.pendingExtractions(), 2) << "Adjacent chunk must be scheduled for boundary faces";
	meshState.extractAllPending();

	size_t vertCount = 0, normalsCount = 0, indCount = 0;
	meshState.count(MeshType_Opaque, 0, vertCount, normalsCount, indCount);
	EXPECT_EQ(indCount, 36u) << "Single voxel at upper boundary should have all 6 faces (36 indices)";

	(void)meshState.shutdown();
}

// https://github.com/vengi-voxel/vengi/issues/844
// Verify that deleting a voxel at a chunk boundary triggers re-extraction
// of the adjacent chunk so that newly-exposed faces appear.
TEST_F(MeshStateTest, testCubicDeleteAdjacentVoxelAcrossChunkBoundary) {
	voxel::RawVolume v(voxel::Region(-1, 16, 1, 3, 19, 4));

	for (int y = 16; y <= 19; ++y) {
		for (int z = 1; z <= 4; ++z) {
			v.setVoxel(-1, y, z, voxel::createVoxel(voxel::VoxelType::Generic, 1));
			for (int x = 0; x <= 3; ++x) {
				v.setVoxel(x, y, z, voxel::createVoxel(voxel::VoxelType::Generic, 2));
			}
		}
	}

	MeshState meshState;
	meshState.construct();
	core::Var::getVar(cfg::VoxelMeshMode)->setVal((int)voxel::SurfaceExtractionType::Cubic);
	meshState.init();
	bool deleted = false;
	palette::Palette pal;
	pal.nippon();
	(void)meshState.setVolume(0, &v, &pal, nullptr, true, deleted);

	meshState.scheduleRegionExtraction(0, v.region());
	meshState.extractAllPending();

	size_t indBefore = 0, vc = 0, nc = 0;
	meshState.count(MeshType_Opaque, 0, vc, nc, indBefore);
	EXPECT_GT(indBefore, 0u);

	// Delete voxels at x=0 (chunk boundary)
	for (int y = 16; y <= 19; ++y) {
		for (int z = 1; z <= 4; ++z) {
			v.setVoxel(0, y, z, voxel::createVoxel(voxel::VoxelType::Air, 0));
		}
	}

	const voxel::Region modifiedRegion(0, 16, 1, 0, 19, 4);
	meshState.scheduleRegionExtraction(0, modifiedRegion);
	EXPECT_GE(meshState.pendingExtractions(), 2) << "Both adjacent chunks must be scheduled";
	meshState.extractAllPending();

	size_t indAfter = 0;
	vc = 0; nc = 0;
	meshState.count(MeshType_Opaque, 0, vc, nc, indAfter);
	EXPECT_GT(indAfter, 0u) << "After deleting adjacent voxel, faces should still exist";

	(void)meshState.shutdown();
}

// Verify that adjacent chunk regions produced by calculateExtractRegion
// never overlap - each voxel position belongs to exactly one chunk.
TEST_F(MeshStateTest, testNoOverlappingExtractRegions) {
	voxel::RawVolume v(voxel::Region(-32, 31));

	MeshState meshState;
	meshState.construct();
	meshState.init();
	bool deleted = false;
	palette::Palette pal;
	pal.nippon();
	(void)meshState.setVolume(0, &v, &pal, nullptr, true, deleted);

	meshState.scheduleRegionExtraction(0, v.region());

	// Collect all scheduled regions
	core::DynamicArray<voxel::Region> regions;
	const int n = meshState.pendingExtractions();
	EXPECT_GT(n, 0);

	// Extract all and collect the regions from the extraction results
	// Since calculateExtractRegion produces grid-aligned non-overlapping chunks,
	// we verify the grid property: mins are multiples of meshSize and
	// maxs = mins + meshSize - 1
	meshState.extractAllPending();

	// Verify by re-scheduling and checking the regions
	meshState.scheduleRegionExtraction(0, v.region());
	// All chunks should tile without gaps or overlaps
	// For volume [-32, 31] with meshSize=16:
	// x chunks: -32..-17, -16..-1, 0..15, 16..31 = 4 chunks per axis
	// Total = 4^3 = 64 chunks, but completeRegion is [-32, 32] so we get
	// an extra layer: 5 chunks in some axes
	const int expected = meshState.pendingExtractions();
	EXPECT_GT(expected, 0);

	(void)meshState.shutdown();
}

// Verify that for a volume entirely within one chunk, only the minimum
// number of chunks are scheduled (the chunk itself + boundary chunks
// from completeRegion shift).
TEST_F(MeshStateTest, testSingleChunkVolume) {
	voxel::RawVolume v(voxel::Region(0, 14));

	MeshState meshState;
	meshState.construct();
	meshState.init();
	bool deleted = false;
	palette::Palette pal;
	pal.nippon();
	(void)meshState.setVolume(0, &v, &pal, nullptr, true, deleted);

	meshState.scheduleRegionExtraction(0, v.region());
	// Volume [0,14] fits in chunk [0,15]. completeRegion = [0,15] (shifted).
	// Only chunk [0,15] should intersect.
	const int n = meshState.pendingExtractions();
	// With meshSizeMinusOne subtraction and floor division, we may get
	// extra chunks, but they should be filtered by completeRegion intersection.
	EXPECT_GE(n, 1);

	(void)meshState.shutdown();
}

// scheduleRegionExtraction must not touch a volume after it was cleared
// (SceneGraph may free the RawVolume once MeshState no longer holds the pointer).
TEST_F(MeshStateTest, testScheduleAfterVolumeCleared) {
	voxel::RawVolume *v = new voxel::RawVolume(voxel::Region(0, 0, 0, 7, 7, 7));
	v->setVoxel(0, 0, 0, voxel::createVoxel(voxel::VoxelType::Generic, 1));

	MeshState meshState;
	meshState.construct();
	meshState.init();
	bool deleted = false;
	palette::Palette pal;
	pal.nippon();
	(void)meshState.setVolume(0, v, &pal, nullptr, true, deleted);
	ASSERT_NE(nullptr, meshState.volume(0));

	meshState.scheduleRegionExtraction(0, v->region());
	(void)meshState.setVolume(0, nullptr, nullptr, nullptr, true, deleted);
	delete v;

	// Must not use-after-free
	EXPECT_FALSE(meshState.scheduleRegionExtraction(0, voxel::Region(0, 0, 0, 7, 7, 7)));
	(void)meshState.shutdown();
}

// Verify that the cubic mesher through MeshState does not produce
// overlapping geometry for a solid block that spans multiple chunks.
TEST_F(MeshStateTest, testCubicNoOverlappingFaces) {
	// 2x2x2 solid block spanning chunk boundary at x=0
	voxel::RawVolume v(voxel::Region(-1, -1, -1, 0, 0, 0));
	for (int x = -1; x <= 0; ++x)
		for (int y = -1; y <= 0; ++y)
			for (int z = -1; z <= 0; ++z)
				v.setVoxel(x, y, z, voxel::createVoxel(voxel::VoxelType::Generic, 1));

	MeshState meshState;
	meshState.construct();
	core::Var::getVar(cfg::VoxelMeshMode)->setVal((int)voxel::SurfaceExtractionType::Cubic);
	meshState.init();
	bool deleted = false;
	palette::Palette pal;
	pal.nippon();
	(void)meshState.setVolume(0, &v, &pal, nullptr, true, deleted);

	meshState.scheduleRegionExtraction(0, v.region());
	meshState.extractAllPending();

	size_t vertCount = 0, normalsCount = 0, indCount = 0;
	meshState.count(MeshType_Opaque, 0, vertCount, normalsCount, indCount);

	// A 2x2x2 cube has 6 faces, each 2x2 = 4 quads = 8 triangles per face.
	// Without merging: 6 * 4 * 2 * 3 = 144 indices.
	// With merging (within each chunk): each face may merge to fewer quads.
	// The key check: no MORE than 144 indices (no duplicates from overlapping chunks).
	EXPECT_GT(indCount, 0u);
	EXPECT_LE(indCount, 144u) << "2x2x2 cube must not have more than 144 indices (no overlapping)";

	(void)meshState.shutdown();
}

// Verify that the binary mesher does not produce overlapping geometry
// for a volume at negative coordinates.
TEST_F(MeshStateTest, testBinaryNoOverlappingFaces) {
	// Single voxel at negative coordinates
	voxel::RawVolume v(voxel::Region(-27, 9, -27, -27, 9, -27));
	v.setVoxel(-27, 9, -27, voxel::createVoxel(voxel::VoxelType::Generic, 1));

	MeshState meshState;
	meshState.construct();
	// Binary is the default from SetUp, but be explicit
	core::Var::getVar(cfg::VoxelMeshMode)->setVal((int)voxel::SurfaceExtractionType::Binary);
	meshState.init();
	bool deleted = false;
	palette::Palette pal;
	pal.nippon();
	(void)meshState.setVolume(0, &v, &pal, nullptr, true, deleted);

	meshState.scheduleRegionExtraction(0, v.region());
	meshState.extractAllPending();

	size_t vertCount = 0, normalsCount = 0, indCount = 0;
	meshState.count(MeshType_Opaque, 0, vertCount, normalsCount, indCount);

	// Single voxel = 6 faces * 2 triangles * 3 indices = 36
	EXPECT_EQ(indCount, 36u) << "Single voxel at (-27,9,-27) should have exactly 36 indices";

	(void)meshState.shutdown();
}

// Verify that extraction regions from scheduleRegionExtraction form a
// proper non-overlapping grid. Two adjacent regions must not share any
// voxel positions.
TEST_F(MeshStateTest, testExtractRegionGridAlignment) {
	// Use a volume that spans exactly 2 chunks in each axis
	const int meshSize = 16; // test mesh size
	voxel::RawVolume v(voxel::Region(0, 0, 0, meshSize * 2 - 1, meshSize * 2 - 1, meshSize * 2 - 1));

	MeshState meshState;
	meshState.construct();
	meshState.init();
	bool deleted = false;
	palette::Palette pal;
	pal.nippon();
	(void)meshState.setVolume(0, &v, &pal, nullptr, true, deleted);

	// Schedule a single voxel at the chunk boundary
	const voxel::Region modifiedRegion(meshSize - 1, 0, 0, meshSize, 0, 0);
	meshState.scheduleRegionExtraction(0, modifiedRegion);

	const int n = meshState.pendingExtractions();
	// Should schedule at least the two chunks that contain the modified voxels
	EXPECT_GE(n, 2);

	(void)meshState.shutdown();
}

/**
 * @brief Check that a mesh has no duplicate triangles (same 3 vertex positions).
 * Duplicate triangles cause z-fighting artifacts.
 */
static int countDuplicateTriangles(const voxel::Mesh &mesh) {
	const voxel::IndexArray &indices = mesh.getIndexVector();
	const voxel::VertexArray &vertices = mesh.getVertexVector();
	const size_t numTris = indices.size() / 3;
	int duplicates = 0;

	for (size_t i = 0; i < numTris; ++i) {
		// Get sorted positions for triangle i
		glm::vec3 pi[3] = {
			vertices[indices[i * 3 + 0]].position,
			vertices[indices[i * 3 + 1]].position,
			vertices[indices[i * 3 + 2]].position
		};
		// Sort vertices for canonical comparison
		if (pi[0].x > pi[1].x || (pi[0].x == pi[1].x && (pi[0].y > pi[1].y || (pi[0].y == pi[1].y && pi[0].z > pi[1].z))))
			core::exchange(pi[0], pi[1]);
		if (pi[1].x > pi[2].x || (pi[1].x == pi[2].x && (pi[1].y > pi[2].y || (pi[1].y == pi[2].y && pi[1].z > pi[2].z))))
			core::exchange(pi[1], pi[2]);
		if (pi[0].x > pi[1].x || (pi[0].x == pi[1].x && (pi[0].y > pi[1].y || (pi[0].y == pi[1].y && pi[0].z > pi[1].z))))
			core::exchange(pi[0], pi[1]);

		for (size_t j = i + 1; j < numTris; ++j) {
			glm::vec3 pj[3] = {
				vertices[indices[j * 3 + 0]].position,
				vertices[indices[j * 3 + 1]].position,
				vertices[indices[j * 3 + 2]].position
			};
			if (pj[0].x > pj[1].x || (pj[0].x == pj[1].x && (pj[0].y > pj[1].y || (pj[0].y == pj[1].y && pj[0].z > pj[1].z))))
				core::exchange(pj[0], pj[1]);
			if (pj[1].x > pj[2].x || (pj[1].x == pj[2].x && (pj[1].y > pj[2].y || (pj[1].y == pj[2].y && pj[1].z > pj[2].z))))
				core::exchange(pj[1], pj[2]);
			if (pj[0].x > pj[1].x || (pj[0].x == pj[1].x && (pj[0].y > pj[1].y || (pj[0].y == pj[1].y && pj[0].z > pj[1].z))))
				core::exchange(pj[0], pj[1]);

			if (pi[0] == pj[0] && pi[1] == pj[1] && pi[2] == pj[2]) {
				++duplicates;
			}
		}
	}
	return duplicates;
}

// Helper to count duplicate triangles across all meshes in a MeshState for a given volume index
static int countAllDuplicateTriangles(const MeshState &meshState, int idx) {
	int total = 0;
	for (int type = 0; type < MeshType_Max; ++type) {
		const auto &meshesMap = meshState.meshes((MeshType)type);
		for (const auto &iter : meshesMap) {
			const MeshState::Meshes &meshes = iter->value;
			if (idx < (int)meshes.size() && meshes[idx] != nullptr) {
				total += countDuplicateTriangles(*meshes[idx]);
			}
		}
	}
	return total;
}

// Verify that extracting a single voxel at various positions never produces
// duplicate triangles (which cause z-fighting).
TEST_F(MeshStateTest, testCubicNoDuplicateTriangles_SingleVoxel) {
	// Test at position (32, 4, 48) which was reported to have artifacts
	const glm::ivec3 positions[] = {
		{32, 4, 48}, {0, 0, 0}, {15, 15, 15}, {61, 0, 0}, {0, 61, 0}, {0, 0, 61}
	};

	for (const auto &pos : positions) {
		voxel::RawVolume v(voxel::Region(0, 0, 0, 63, 63, 63));
		v.setVoxel(pos.x, pos.y, pos.z, voxel::createVoxel(voxel::VoxelType::Generic, 1));

		MeshState meshState;
		meshState.construct();
		core::Var::getVar(cfg::VoxelMeshMode)->setVal((int)voxel::SurfaceExtractionType::Cubic);
		meshState.init();
		bool deleted = false;
		palette::Palette pal;
		pal.nippon();
		(void)meshState.setVolume(0, &v, &pal, nullptr, true, deleted);

		meshState.scheduleRegionExtraction(0, v.region());
		meshState.extractAllPending();

		const int dups = countAllDuplicateTriangles(meshState, 0);
		EXPECT_EQ(dups, 0) << "Duplicate triangles at position (" << pos.x << "," << pos.y << "," << pos.z << ")";

		size_t vc = 0, nc = 0, ic = 0;
		meshState.count(MeshType_Opaque, 0, vc, nc, ic);
		EXPECT_EQ(ic, 36u) << "Single voxel should have 36 indices at (" << pos.x << "," << pos.y << "," << pos.z << ")";

		(void)meshState.shutdown();
	}
}

// Verify that extracting a full volume never produces duplicate triangles
// across chunk boundaries.
TEST_F(MeshStateTest, testCubicNoDuplicateTriangles_FullVolume) {
	// Small volume that spans chunk boundaries (meshSize=16 in tests)
	voxel::RawVolume v(voxel::Region(0, 0, 0, 31, 3, 47));
	for (int x = 0; x <= 31; ++x)
		for (int y = 0; y <= 3; ++y)
			for (int z = 0; z <= 47; ++z)
				v.setVoxel(x, y, z, voxel::createVoxel(voxel::VoxelType::Generic, 1));

	MeshState meshState;
	meshState.construct();
	core::Var::getVar(cfg::VoxelMeshMode)->setVal((int)voxel::SurfaceExtractionType::Cubic);
	meshState.init();
	bool deleted = false;
	palette::Palette pal;
	pal.nippon();
	(void)meshState.setVolume(0, &v, &pal, nullptr, true, deleted);

	meshState.scheduleRegionExtraction(0, v.region());
	meshState.extractAllPending();

	const int dups = countAllDuplicateTriangles(meshState, 0);
	EXPECT_EQ(dups, 0) << "Full volume should have no duplicate triangles across chunk boundaries";

	(void)meshState.shutdown();
}

// Same test for the binary mesher
TEST_F(MeshStateTest, testBinaryNoDuplicateTriangles_FullVolume) {
	voxel::RawVolume v(voxel::Region(0, 0, 0, 31, 3, 47));
	for (int x = 0; x <= 31; ++x)
		for (int y = 0; y <= 3; ++y)
			for (int z = 0; z <= 47; ++z)
				v.setVoxel(x, y, z, voxel::createVoxel(voxel::VoxelType::Generic, 1));

	MeshState meshState;
	meshState.construct();
	core::Var::getVar(cfg::VoxelMeshMode)->setVal((int)voxel::SurfaceExtractionType::Binary);
	meshState.init();
	bool deleted = false;
	palette::Palette pal;
	pal.nippon();
	(void)meshState.setVolume(0, &v, &pal, nullptr, true, deleted);

	meshState.scheduleRegionExtraction(0, v.region());
	meshState.extractAllPending();

	const int dups = countAllDuplicateTriangles(meshState, 0);
	EXPECT_EQ(dups, 0) << "Binary mesher should have no duplicate triangles across chunk boundaries";

	(void)meshState.shutdown();
}

} // namespace voxelrender
