#!/usr/bin/env bash
# Validate WiX installer sources on Linux without requiring the WiX toolset.
# Checks XML well-formedness and cross-references between the patch file
# and the extra wxs sources.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
WIXPATCH="${SCRIPT_DIR}/wixpatch.xml"
FILEASSOC="${SCRIPT_DIR}/fileassoc.wxs"
# thumbnailer.wix.in, voxconvert.wxs, and palconvert.wxs are generated by CMake into the build directory
BUILD_DIR="${1:-}"
ERRORS=0

error() {
	echo "ERROR: $*" >&2
	ERRORS=$((ERRORS + 1))
}

warn() {
	echo "WARN: $*" >&2
}

# check dependencies
if ! command -v xmllint >/dev/null 2>&1; then
	echo "xmllint not found - install libxml2-utils" >&2
	exit 1
fi

echo "Validating WiX installer sources..."

# 1) XML well-formedness
CHECKED_FILES=("$WIXPATCH" "$FILEASSOC")
# Validate the .wxs.in templates (strip @placeholders@ first)
for wixin in "${SCRIPT_DIR}"/*.wxs.in; do
	if [ -f "$wixin" ]; then
		fname=$(basename "$wixin")
		if sed 's/@[A-Z_]*@//g' "$wixin" | xmllint --noout - 2>/dev/null; then
			echo "  OK: $fname is well-formed XML"
		else
			error "$fname is not well-formed XML (after placeholder removal)"
		fi
	fi
done
if [ -n "$BUILD_DIR" ]; then
	for gen in thumbnailer.wxs voxconvert.wxs palconvert.wxs; do
		if [ -f "$BUILD_DIR/$gen" ]; then
			CHECKED_FILES+=("$BUILD_DIR/$gen")
		fi
	done
fi
for f in "${CHECKED_FILES[@]}"; do
	if [ ! -f "$f" ]; then
		error "Missing file: $f"
		continue
	fi
	if ! xmllint --noout "$f" 2>/dev/null; then
		error "$f is not well-formed XML"
	else
		echo "  OK: $(basename "$f") is well-formed XML"
	fi
done

if [ "$ERRORS" -gt 0 ]; then
	echo "$ERRORS error(s) found."
	exit 1
fi

# 2) Check that the ComponentGroupRef in wixpatch.xml matches the ComponentGroup in fileassoc.wxs
REFS=$(grep -oP 'ComponentGroupRef Id="\K[^"]+' "$WIXPATCH" || true)
DEFINED_GROUPS=$(grep -oP 'ComponentGroup Id="\K[^"]+' "$FILEASSOC" || true)

for ref in $REFS; do
	found=0
	for grp in $DEFINED_GROUPS; do
		if [ "$grp" = "$ref" ]; then
			found=1
			break
		fi
	done
	if [ "$found" -eq 0 ]; then
		error "wixpatch.xml references ComponentGroup '$ref' but it is not defined in fileassoc.wxs"
	fi
done

# 3) Check that every ComponentRef in fileassoc.wxs has a matching Component
COMPONENT_IDS=$(grep -oP 'Component Id="\K[^"]+' "$FILEASSOC" | sort -u)
COMPONENT_REFS=$(grep -oP 'ComponentRef Id="\K[^"]+' "$FILEASSOC" | sort -u)

MISSING_COMPONENTS=$(comm -23 <(echo "$COMPONENT_REFS") <(echo "$COMPONENT_IDS"))
if [ -n "$MISSING_COMPONENTS" ]; then
	while IFS= read -r ref; do
		error "fileassoc.wxs: ComponentRef '$ref' has no matching Component"
	done <<< "$MISSING_COMPONENTS"
fi

# and the reverse - components without refs
UNREFERENCED=$(comm -23 <(echo "$COMPONENT_IDS") <(echo "$COMPONENT_REFS"))
if [ -n "$UNREFERENCED" ]; then
	while IFS= read -r id; do
		warn "fileassoc.wxs: Component '$id' is not referenced by any ComponentRef"
	done <<< "$UNREFERENCED"
fi

# 4) Check for duplicate Component IDs
DUPES=$(grep -oP 'Component Id="\K[^"]+' "$FILEASSOC" | sort | uniq -d || true)
if [ -n "$DUPES" ]; then
	while IFS= read -r dup; do
		error "fileassoc.wxs: Duplicate Component Id '$dup'"
	done <<< "$DUPES"
fi

# 5) Check for duplicate ProgId values
PROGID_DUPES=$(grep -oP 'ProgId Id="\K[^"]+' "$FILEASSOC" | sort | uniq -d || true)
if [ -n "$PROGID_DUPES" ]; then
	while IFS= read -r dup; do
		error "fileassoc.wxs: Duplicate ProgId '$dup'"
	done <<< "$PROGID_DUPES"
fi

# 6) Check that Fragment IDs in wixpatch.xml are non-empty
EMPTY_FRAGS=$(grep -cP 'CPackWiXFragment Id=""' "$WIXPATCH" || true)
if [ "$EMPTY_FRAGS" -gt 0 ]; then
	error "wixpatch.xml has $EMPTY_FRAGS fragment(s) with empty Id"
fi

# 7) Check for BOM (common issue noted in the file comment)
for f in "${CHECKED_FILES[@]}"; do
	if [ ! -f "$f" ]; then
		continue
	fi
	if head -c3 "$f" | grep -qP '\xEF\xBB\xBF'; then
		error "$(basename "$f") has a UTF-8 BOM - remove it"
	fi
done

# 8) Validate standalone installers: ComponentRef/Component matching
STANDALONE_FILES=()
if [ -n "$BUILD_DIR" ]; then
	for gen in thumbnailer.wxs voxconvert.wxs palconvert.wxs; do
		if [ -f "$BUILD_DIR/$gen" ]; then
			STANDALONE_FILES+=("$BUILD_DIR/$gen")
		fi
	done
fi
for f in "${STANDALONE_FILES[@]}"; do
	if [ ! -f "$f" ]; then
		continue
	fi
	fname=$(basename "$f")
	IDS=$(grep -oP 'Component Id="\K[^"]+' "$f" | sort -u)
	CREFS=$(grep -oP 'ComponentRef Id="\K[^"]+' "$f" | sort -u)

	MISSING=$(comm -23 <(echo "$CREFS") <(echo "$IDS"))
	if [ -n "$MISSING" ]; then
		while IFS= read -r ref; do
			error "$fname: ComponentRef '$ref' has no matching Component"
		done <<< "$MISSING"
	fi

	DUP_IDS=$(grep -oP 'Component Id="\K[^"]+' "$f" | sort | uniq -d || true)
	if [ -n "$DUP_IDS" ]; then
		while IFS= read -r dup; do
			error "$fname: Duplicate Component Id '$dup'"
		done <<< "$DUP_IDS"
	fi
done

if [ "$ERRORS" -gt 0 ]; then
	echo "$ERRORS error(s) found."
	exit 1
fi

echo "All WiX validation checks passed."
