#pragma once

#include "NNode.h"

CREATE_RESULT_NODE(Add);
CREATE_RESULT_NODE(Multiply);
CREATE_RESULT_NODE(Divide);
CREATE_RESULT_NODE(Subtract);
CREATE_RESULT_NODE(MinNoise);
CREATE_RESULT_NODE(MaxNoise);
