/**
 * @file
 */

#include "GimpPalette.h"
#include "core/Log.h"
#include "core/StringUtil.h"
#include "engine-config.h"

namespace voxel {

bool GimpPalette::load(const core::String &filename, io::SeekableReadStream &stream, voxel::Palette &palette) {
	char line[2048];

	int colorCount = 0;
	while (stream.readLine(sizeof(line), line)) {
		if (strncmp("#Palette Name", line, 13) == 0) {
			// _name = line + 13;
			// if (_name[0] == ':') {
			// 	_name = _name.substr(1);
			// }
			// _name = _name.trim();
			// Log::debug("found name %s", _name.c_str());
			continue;
		}
		if (strncmp("Name", line, 4) == 0) {
			// _name = line + 4;
			// if (_name[0] == ':') {
			// 	_name = _name.substr(1);
			// }
			// _name = _name.trim();
			// Log::debug("found name %s", _name.c_str());
			continue;
		}
		if (line[0] == '#') {
			Log::debug("skip comment line: %s", line);
			continue;
		}
		if (strcmp("GIMP Palette", line) == 0) {
			continue;
		}

		int r, g, b;
		if (SDL_sscanf(line, "%i %i %i", &r, &g, &b) != 3) {
			Log::error("Failed to parse line '%s'", line);
			continue;
		}
		if (colorCount >= PaletteMaxColors) {
			Log::warn("Not all colors were loaded");
			break;
		}
		palette.setColor(colorCount, core::RGBA(r, g, b));
		++colorCount;
	}
	palette.setSize(colorCount);
	return colorCount > 0;
}

bool GimpPalette::save(const voxel::Palette &palette, const core::String &filename, io::SeekableWriteStream &stream) {
	stream.writeLine("GIMP Palette");
	stream.writeStringFormat(false, "Name: %s\n", palette.name().c_str());
	stream.writeStringFormat(false, "#Palette Name: %s\n", palette.name().c_str());
	stream.writeLine("# Generated by vengi " PROJECT_VERSION " github.com/mgerhardy/vengi");
	for (size_t i = 0; i < palette.size(); ++i) {
		const core::RGBA &color = palette.color(i);
		stream.writeStringFormat(false, "%3i %3i %3i\tcolor index %i\n", color.r, color.g, color.b, (int)i);
	}
	return true;
}

} // namespace voxel
