// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_SERVERMESSAGES_NETWORK_MESSAGES_SERVER_H_
#define FLATBUFFERS_GENERATED_SERVERMESSAGES_NETWORK_MESSAGES_SERVER_H_

#include "flatbuffers/flatbuffers.h"

#include "Shared_generated.h"

namespace network {
namespace messages {
struct Vec3;
struct Vec2;
}  // namespace messages
}  // namespace network

namespace network {
namespace messages {
namespace server {

struct Seed;
struct AuthFailed;
struct UserSpawn;
struct UserUpdate;
struct NpcSpawn;
struct NpcTakeOver;
struct NpcRemove;
struct NpcUpdate;
struct NpcAnim;
struct NpcEffect;
struct ServerMessage;

enum Type {
  Type_NONE = 0,
  Type_Seed = 1,
  Type_UserSpawn = 2,
  Type_UserUpdate = 3,
  Type_NpcSpawn = 4,
  Type_NpcRemove = 5,
  Type_NpcUpdate = 6,
  Type_NpcAnim = 7,
  Type_NpcEffect = 8,
  Type_AuthFailed = 9,
  Type_NpcTakeOver = 10
};

inline const char **EnumNamesType() {
  static const char *names[] = { "NONE", "Seed", "UserSpawn", "UserUpdate", "NpcSpawn", "NpcRemove", "NpcUpdate", "NpcAnim", "NpcEffect", "AuthFailed", "NpcTakeOver", nullptr };
  return names;
}

inline const char *EnumNameType(Type e) { return EnumNamesType()[e]; }

inline bool VerifyType(flatbuffers::Verifier &verifier, const void *union_obj, Type type);

struct Seed FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  int64_t seed() const { return GetField<int64_t>(4, 0); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int64_t>(verifier, 4 /* seed */) &&
           verifier.EndTable();
  }
};

struct SeedBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_seed(int64_t seed) { fbb_.AddElement<int64_t>(4, seed, 0); }
  SeedBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  SeedBuilder &operator=(const SeedBuilder &);
  flatbuffers::Offset<Seed> Finish() {
    auto o = flatbuffers::Offset<Seed>(fbb_.EndTable(start_, 1));
    return o;
  }
};

inline flatbuffers::Offset<Seed> CreateSeed(flatbuffers::FlatBufferBuilder &_fbb,
   int64_t seed = 0) {
  SeedBuilder builder_(_fbb);
  builder_.add_seed(seed);
  return builder_.Finish();
}

struct AuthFailed FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct AuthFailedBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  AuthFailedBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  AuthFailedBuilder &operator=(const AuthFailedBuilder &);
  flatbuffers::Offset<AuthFailed> Finish() {
    auto o = flatbuffers::Offset<AuthFailed>(fbb_.EndTable(start_, 0));
    return o;
  }
};

inline flatbuffers::Offset<AuthFailed> CreateAuthFailed(flatbuffers::FlatBufferBuilder &_fbb) {
  AuthFailedBuilder builder_(_fbb);
  return builder_.Finish();
}

struct UserSpawn FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  int64_t id() const { return GetField<int64_t>(4, 0); }
  const flatbuffers::String *name() const { return GetPointer<const flatbuffers::String *>(6); }
  const network::messages::Vec3 *pos() const { return GetStruct<const network::messages::Vec3 *>(8); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int64_t>(verifier, 4 /* id */) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, 6 /* name */) &&
           verifier.Verify(name()) &&
           VerifyField<network::messages::Vec3>(verifier, 8 /* pos */) &&
           verifier.EndTable();
  }
};

struct UserSpawnBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_id(int64_t id) { fbb_.AddElement<int64_t>(4, id, 0); }
  void add_name(flatbuffers::Offset<flatbuffers::String> name) { fbb_.AddOffset(6, name); }
  void add_pos(const network::messages::Vec3 *pos) { fbb_.AddStruct(8, pos); }
  UserSpawnBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  UserSpawnBuilder &operator=(const UserSpawnBuilder &);
  flatbuffers::Offset<UserSpawn> Finish() {
    auto o = flatbuffers::Offset<UserSpawn>(fbb_.EndTable(start_, 3));
    return o;
  }
};

inline flatbuffers::Offset<UserSpawn> CreateUserSpawn(flatbuffers::FlatBufferBuilder &_fbb,
   int64_t id = 0,
   flatbuffers::Offset<flatbuffers::String> name = 0,
   const network::messages::Vec3 *pos = 0) {
  UserSpawnBuilder builder_(_fbb);
  builder_.add_id(id);
  builder_.add_pos(pos);
  builder_.add_name(name);
  return builder_.Finish();
}

struct UserUpdate FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  const network::messages::Vec3 *pos() const { return GetStruct<const network::messages::Vec3 *>(4); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<network::messages::Vec3>(verifier, 4 /* pos */) &&
           verifier.EndTable();
  }
};

struct UserUpdateBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_pos(const network::messages::Vec3 *pos) { fbb_.AddStruct(4, pos); }
  UserUpdateBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  UserUpdateBuilder &operator=(const UserUpdateBuilder &);
  flatbuffers::Offset<UserUpdate> Finish() {
    auto o = flatbuffers::Offset<UserUpdate>(fbb_.EndTable(start_, 1));
    return o;
  }
};

inline flatbuffers::Offset<UserUpdate> CreateUserUpdate(flatbuffers::FlatBufferBuilder &_fbb,
   const network::messages::Vec3 *pos = 0) {
  UserUpdateBuilder builder_(_fbb);
  builder_.add_pos(pos);
  return builder_.Finish();
}

struct NpcSpawn FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  int64_t id() const { return GetField<int64_t>(4, 0); }
  network::messages::NpcType type() const { return static_cast<network::messages::NpcType>(GetField<int32_t>(6, 0)); }
  const network::messages::Vec3 *pos() const { return GetStruct<const network::messages::Vec3 *>(8); }
  int64_t human() const { return GetField<int64_t>(10, -1); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int64_t>(verifier, 4 /* id */) &&
           VerifyField<int32_t>(verifier, 6 /* type */) &&
           VerifyField<network::messages::Vec3>(verifier, 8 /* pos */) &&
           VerifyField<int64_t>(verifier, 10 /* human */) &&
           verifier.EndTable();
  }
};

struct NpcSpawnBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_id(int64_t id) { fbb_.AddElement<int64_t>(4, id, 0); }
  void add_type(network::messages::NpcType type) { fbb_.AddElement<int32_t>(6, static_cast<int32_t>(type), 0); }
  void add_pos(const network::messages::Vec3 *pos) { fbb_.AddStruct(8, pos); }
  void add_human(int64_t human) { fbb_.AddElement<int64_t>(10, human, -1); }
  NpcSpawnBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  NpcSpawnBuilder &operator=(const NpcSpawnBuilder &);
  flatbuffers::Offset<NpcSpawn> Finish() {
    auto o = flatbuffers::Offset<NpcSpawn>(fbb_.EndTable(start_, 4));
    return o;
  }
};

inline flatbuffers::Offset<NpcSpawn> CreateNpcSpawn(flatbuffers::FlatBufferBuilder &_fbb,
   int64_t id = 0,
   network::messages::NpcType type = network::messages::NpcType_NONE,
   const network::messages::Vec3 *pos = 0,
   int64_t human = -1) {
  NpcSpawnBuilder builder_(_fbb);
  builder_.add_human(human);
  builder_.add_id(id);
  builder_.add_pos(pos);
  builder_.add_type(type);
  return builder_.Finish();
}

struct NpcTakeOver FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  int64_t id() const { return GetField<int64_t>(4, 0); }
  int64_t human() const { return GetField<int64_t>(6, -1); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int64_t>(verifier, 4 /* id */) &&
           VerifyField<int64_t>(verifier, 6 /* human */) &&
           verifier.EndTable();
  }
};

struct NpcTakeOverBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_id(int64_t id) { fbb_.AddElement<int64_t>(4, id, 0); }
  void add_human(int64_t human) { fbb_.AddElement<int64_t>(6, human, -1); }
  NpcTakeOverBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  NpcTakeOverBuilder &operator=(const NpcTakeOverBuilder &);
  flatbuffers::Offset<NpcTakeOver> Finish() {
    auto o = flatbuffers::Offset<NpcTakeOver>(fbb_.EndTable(start_, 2));
    return o;
  }
};

inline flatbuffers::Offset<NpcTakeOver> CreateNpcTakeOver(flatbuffers::FlatBufferBuilder &_fbb,
   int64_t id = 0,
   int64_t human = -1) {
  NpcTakeOverBuilder builder_(_fbb);
  builder_.add_human(human);
  builder_.add_id(id);
  return builder_.Finish();
}

struct NpcRemove FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  int64_t id() const { return GetField<int64_t>(4, 0); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int64_t>(verifier, 4 /* id */) &&
           verifier.EndTable();
  }
};

struct NpcRemoveBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_id(int64_t id) { fbb_.AddElement<int64_t>(4, id, 0); }
  NpcRemoveBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  NpcRemoveBuilder &operator=(const NpcRemoveBuilder &);
  flatbuffers::Offset<NpcRemove> Finish() {
    auto o = flatbuffers::Offset<NpcRemove>(fbb_.EndTable(start_, 1));
    return o;
  }
};

inline flatbuffers::Offset<NpcRemove> CreateNpcRemove(flatbuffers::FlatBufferBuilder &_fbb,
   int64_t id = 0) {
  NpcRemoveBuilder builder_(_fbb);
  builder_.add_id(id);
  return builder_.Finish();
}

struct NpcUpdate FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  int64_t id() const { return GetField<int64_t>(4, 0); }
  const network::messages::Vec3 *pos() const { return GetStruct<const network::messages::Vec3 *>(6); }
  float rotation() const { return GetField<float>(8, 0); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int64_t>(verifier, 4 /* id */) &&
           VerifyFieldRequired<network::messages::Vec3>(verifier, 6 /* pos */) &&
           VerifyField<float>(verifier, 8 /* rotation */) &&
           verifier.EndTable();
  }
};

struct NpcUpdateBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_id(int64_t id) { fbb_.AddElement<int64_t>(4, id, 0); }
  void add_pos(const network::messages::Vec3 *pos) { fbb_.AddStruct(6, pos); }
  void add_rotation(float rotation) { fbb_.AddElement<float>(8, rotation, 0); }
  NpcUpdateBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  NpcUpdateBuilder &operator=(const NpcUpdateBuilder &);
  flatbuffers::Offset<NpcUpdate> Finish() {
    auto o = flatbuffers::Offset<NpcUpdate>(fbb_.EndTable(start_, 3));
    fbb_.Required(o, 6);  // pos
    return o;
  }
};

inline flatbuffers::Offset<NpcUpdate> CreateNpcUpdate(flatbuffers::FlatBufferBuilder &_fbb,
   int64_t id = 0,
   const network::messages::Vec3 *pos = 0,
   float rotation = 0) {
  NpcUpdateBuilder builder_(_fbb);
  builder_.add_id(id);
  builder_.add_rotation(rotation);
  builder_.add_pos(pos);
  return builder_.Finish();
}

struct NpcAnim FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  int64_t id() const { return GetField<int64_t>(4, 0); }
  uint8_t anim() const { return GetField<uint8_t>(6, 0); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int64_t>(verifier, 4 /* id */) &&
           VerifyField<uint8_t>(verifier, 6 /* anim */) &&
           verifier.EndTable();
  }
};

struct NpcAnimBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_id(int64_t id) { fbb_.AddElement<int64_t>(4, id, 0); }
  void add_anim(uint8_t anim) { fbb_.AddElement<uint8_t>(6, anim, 0); }
  NpcAnimBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  NpcAnimBuilder &operator=(const NpcAnimBuilder &);
  flatbuffers::Offset<NpcAnim> Finish() {
    auto o = flatbuffers::Offset<NpcAnim>(fbb_.EndTable(start_, 2));
    return o;
  }
};

inline flatbuffers::Offset<NpcAnim> CreateNpcAnim(flatbuffers::FlatBufferBuilder &_fbb,
   int64_t id = 0,
   uint8_t anim = 0) {
  NpcAnimBuilder builder_(_fbb);
  builder_.add_id(id);
  builder_.add_anim(anim);
  return builder_.Finish();
}

struct NpcEffect FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  int64_t id() const { return GetField<int64_t>(4, 0); }
  network::messages::NpcEffectType type() const { return static_cast<network::messages::NpcEffectType>(GetField<int32_t>(6, 0)); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int64_t>(verifier, 4 /* id */) &&
           VerifyField<int32_t>(verifier, 6 /* type */) &&
           verifier.EndTable();
  }
};

struct NpcEffectBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_id(int64_t id) { fbb_.AddElement<int64_t>(4, id, 0); }
  void add_type(network::messages::NpcEffectType type) { fbb_.AddElement<int32_t>(6, static_cast<int32_t>(type), 0); }
  NpcEffectBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  NpcEffectBuilder &operator=(const NpcEffectBuilder &);
  flatbuffers::Offset<NpcEffect> Finish() {
    auto o = flatbuffers::Offset<NpcEffect>(fbb_.EndTable(start_, 2));
    return o;
  }
};

inline flatbuffers::Offset<NpcEffect> CreateNpcEffect(flatbuffers::FlatBufferBuilder &_fbb,
   int64_t id = 0,
   network::messages::NpcEffectType type = network::messages::NpcEffectType_HUMAN_CONTROLLED) {
  NpcEffectBuilder builder_(_fbb);
  builder_.add_id(id);
  builder_.add_type(type);
  return builder_.Finish();
}

struct ServerMessage FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  Type data_type() const { return static_cast<Type>(GetField<uint8_t>(4, 0)); }
  const void *data() const { return GetPointer<const void *>(6); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, 4 /* data_type */) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, 6 /* data */) &&
           VerifyType(verifier, data(), data_type()) &&
           verifier.EndTable();
  }
};

struct ServerMessageBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_data_type(Type data_type) { fbb_.AddElement<uint8_t>(4, static_cast<uint8_t>(data_type), 0); }
  void add_data(flatbuffers::Offset<void> data) { fbb_.AddOffset(6, data); }
  ServerMessageBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  ServerMessageBuilder &operator=(const ServerMessageBuilder &);
  flatbuffers::Offset<ServerMessage> Finish() {
    auto o = flatbuffers::Offset<ServerMessage>(fbb_.EndTable(start_, 2));
    return o;
  }
};

inline flatbuffers::Offset<ServerMessage> CreateServerMessage(flatbuffers::FlatBufferBuilder &_fbb,
   Type data_type = Type_NONE,
   flatbuffers::Offset<void> data = 0) {
  ServerMessageBuilder builder_(_fbb);
  builder_.add_data(data);
  builder_.add_data_type(data_type);
  return builder_.Finish();
}

inline bool VerifyType(flatbuffers::Verifier &verifier, const void *union_obj, Type type) {
  switch (type) {
    case Type_NONE: return true;
    case Type_Seed: return verifier.VerifyTable(reinterpret_cast<const Seed *>(union_obj));
    case Type_UserSpawn: return verifier.VerifyTable(reinterpret_cast<const UserSpawn *>(union_obj));
    case Type_UserUpdate: return verifier.VerifyTable(reinterpret_cast<const UserUpdate *>(union_obj));
    case Type_NpcSpawn: return verifier.VerifyTable(reinterpret_cast<const NpcSpawn *>(union_obj));
    case Type_NpcRemove: return verifier.VerifyTable(reinterpret_cast<const NpcRemove *>(union_obj));
    case Type_NpcUpdate: return verifier.VerifyTable(reinterpret_cast<const NpcUpdate *>(union_obj));
    case Type_NpcAnim: return verifier.VerifyTable(reinterpret_cast<const NpcAnim *>(union_obj));
    case Type_NpcEffect: return verifier.VerifyTable(reinterpret_cast<const NpcEffect *>(union_obj));
    case Type_AuthFailed: return verifier.VerifyTable(reinterpret_cast<const AuthFailed *>(union_obj));
    case Type_NpcTakeOver: return verifier.VerifyTable(reinterpret_cast<const NpcTakeOver *>(union_obj));
    default: return false;
  }
}

inline const ServerMessage *GetServerMessage(const void *buf) { return flatbuffers::GetRoot<ServerMessage>(buf); }

inline bool VerifyServerMessageBuffer(flatbuffers::Verifier &verifier) { return verifier.VerifyBuffer<ServerMessage>(); }

inline void FinishServerMessageBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<ServerMessage> root) { fbb.Finish(root); }

}  // namespace server
}  // namespace messages
}  // namespace network

#endif  // FLATBUFFERS_GENERATED_SERVERMESSAGES_NETWORK_MESSAGES_SERVER_H_
