if (DEFINED ENV{SDL2DIR})
	set(SDL2_INCLUDE_DIRS ENV{SDL2DIR}/include)
	if (FIPS_WINDOWS)
		set(SDL2_LIBRARIES ENV{SDL2DIR}/libs/SDL_main.lib ENV{SDL2DIR}/libs/SDL.lib)
	endif()
else()
	if (FIPS_WINDOWS)
		find_package(SDL REQUIRED)
		set(SDL2_INCLUDE_DIRS ${SDL_INCLUDE_DIRS})
		set(SDL2_LIBRARIES ${SDL_LIBRARIES})
	else()
		#include(FindPkgConfig)
		find_package(PkgConfig)
		if (PKG_CONFIG_FOUND)
			pkg_search_module(SDL2 REQUIRED sdl2)
		endif()
	endif()
endif()
