/**
 * @file
 */

#pragma once

#include "Types.h"
#include "core/collection/DynamicStringMap.h"

namespace video {

typedef core::DynamicStringMap<Uniform> ShaderUniforms;
typedef core::DynamicStringMap<int> ShaderAttributes;

/**
 * @brief Describes a single descriptor binding for a shader program.
 * Generated by shadertool and registered at shader setup time.
 */
struct ShaderResourceBinding {
	enum Type : uint8_t {
		UniformBuffer = 1,
		CombinedImageSampler = 2
	};
	uint8_t binding;
	Type type;
	uint8_t stageFlags; // 1=vertex, 2=fragment, 4=geometry, 8=compute
};

}
