/**
 * @file
 */

#pragma once

#include "core/String.h"
#include "core/collection/List.h"
#include "core/NonCopyable.h"
#include "core/collection/DynamicStringMap.h"
#include <stdint.h>
#include <string.h>
#include <glm/fwd.hpp>
#include "Types.h"

namespace video {

#ifndef VERTEX_POSTFIX
#define VERTEX_POSTFIX ".vert"
#endif

#ifndef FRAGMENT_POSTFIX
#define FRAGMENT_POSTFIX ".frag"
#endif

#ifndef GEOMETRY_POSTFIX
#define GEOMETRY_POSTFIX ".geom"
#endif

#ifndef COMPUTE_POSTFIX
#define COMPUTE_POSTFIX ".comp"
#endif

/**
 * @brief Shader wrapper for GLSL. See shadertool for autogenerated shader wrapper code
 * from vertex and fragment shaders
 * @ingroup Video
 */
class Shader : public core::NonCopyable {
protected:
	typedef core::Array<Id, (int)ShaderType::Max> ShaderArray;
	ShaderArray _shader;

	typedef core::DynamicMap<int, uint64_t, 8> UniformStateMap;
	mutable UniformStateMap _uniformStateMap;

	Id _program = InvalidId;
	bool _initialized = false;
	mutable bool _active = false;
	bool _dirty = true;

	typedef core::DynamicStringMap<core::String> ShaderDefines;
	ShaderDefines _defines;

	mutable uint32_t _time = 0u;

	core::String _name;

	bool createProgramFromShaders();

	/**
	 * @param[in] location The uniform location in the shader
	 * @param[in] value The buffer with the data
	 * @param[in] length The length in bytes of the given value buffer
	 * @return @c false if no change is needed, @c true if we have to update the value
	 */
	bool checkUniformCache(int location, const void* value, int length) const;

public:
	Shader();
	virtual ~Shader();

	/**
	 * Some drivers don't support underscores in their defines...
	 */
	static core::String validPreprocessorName(const core::String& name);

	static int glslVersion;

	virtual void shutdown();

	bool load(const core::String& name, const core::String& buffer, ShaderType shaderType);

	/**
	 * @brief Load a SPIR-V binary into the shader. Falls back to GLSL if the extension is not available.
	 * @param name Human-readable shader name for logging.
	 * @param spirv Pointer to the SPIR-V binary data.
	 * @param spirvSize Size in bytes of the SPIR-V binary.
	 * @param shaderType The shader stage type.
	 * @return @c true on success, @c false if SPIR-V loading is not supported or failed.
	 */
	bool loadSPIRV(const core::String& name, const uint8_t* spirv, size_t spirvSize, ShaderType shaderType);

	core::String getSource(ShaderType shaderType, const core::String& buffer, bool finalize = true, core::List<core::String>* includedFiles = nullptr) const;

	Id handle() const;

	/**
	 * If the shaders were loaded manually via @c ::load, then you have to initialize the shader manually, too
	 */
	bool init();

	bool isInitialized() const;

	/**
	 * @brief The dirty state can be used to determine whether you have to set some
	 * uniforms again because the shader was reinitialized. This must be used manually
	 * if you set e.g. uniforms only once after init
	 * @sa isDirty()
	 */
	void markClean();
	/**
	 * @sa markClean()
	 */
	void markDirty();
	/**
	 * @sa markClean()
	 */
	bool isDirty() const;

	/**
	 * @brief Make sure to configure feedback transform varying before you link the shader
	 * @see setupTransformFeedback()
	 */
	virtual bool setup() {
		return false;
	}

	bool loadFromFile(const core::String& filename, ShaderType shaderType);

	/**
	 * @brief Loads a vertex and fragment shader for the given base filename.
	 *
	 * The filename is hand over to your @c Context implementation with the appropriate filename postfixes
	 *
	 * @see VERTEX_POSTFIX
	 * @see FRAGMENT_POSTFIX
	 */
	bool loadProgram(const core::String& filename);
	bool reload();

	/**
	 * @brief Returns the raw shader handle
	 */
	Id getShader(ShaderType shaderType) const;

	/**
	 * @brief Ticks the shader
	 */
	virtual void update(uint32_t deltaTime);

	/**
	 * @brief Bind the shader program
	 *
	 * @return @c true if is is useable now, @c false if not
	 */
	virtual bool activate() const;

	virtual bool deactivate() const;

	bool isActive() const;

	/**
	 * @brief Run the compute shader.
	 * @return @c false if this is no compute shader, or the execution failed.
	 */
	bool run(const glm::uvec3& workGroups, MemoryBarrierType wait = MemoryBarrierType::None);

	/**
	 * @brief Adds a new define in the form '#define value' to the shader source code
	 */
	void addDefine(const core::String& name, const core::String& value);

	void setUniform(int location, TextureUnit value) const;

	// particular renderer api must implement this

private:
	// only called from setting the texture units
	void setUniformi(int location, int value) const;
};

inline bool Shader::isDirty() const {
	return _dirty;
}

inline bool Shader::isInitialized() const {
	return _initialized;
}

inline void Shader::setUniform(int location, TextureUnit value) const {
	setUniformi(location, core::enumVal(value));
}

inline Id Shader::handle() const {
	return _program;
}

/**
 * @brief Activates the given given and disables it again (if it wasn't active before)
 * if the scope is left
 */
class ScopedShader {
private:
	const Shader& _shader;
	const Id _oldShader;
	bool _alreadyActive;
public:
	ScopedShader(const Shader& shader);
	~ScopedShader();
};

}
