/**
 * @file
 */

#pragma once

#define TITLE_STATUSBAR "##statusbar"
#define TITLE_PALETTE "###palettepanel"
#define TITLE_NORMALPALETTE "###normalpalettepanel"
#define TITLE_NODE_INSPECTOR "###nodeinspectorpanel"
#define TITLE_NODE_PROPERTIES "###nodepropertiespanel"
#define TITLE_VOLUME_INSPECTOR "###nodeinspectorpanel"
#define TITLE_ANIMATION_TIMELINE "###animationtimeline"
#define TITLE_TOOLS "###toolspanel"
#define TITLE_MEMENTO "###mementopanel"
#define TITLE_CAMERA "###camerapanel"
#define TITLE_SCENEDEBUGPANEL "###scenedebugpanel"
#define TITLE_ASSET "###assetpanel"
#define TITLE_SCRIPT "###scriptpanel"
#define TITLE_NETWORK "###networkpanel"
#define TITLE_GAMEMODE "###gamemodepanel"
#define TITLE_SCENEGRAPH "###scenegraph"
#define TITLE_RENDER "###renderpanel"
#define TITLE_RENDERSETTINGS "###rendersettingspanel"
#define TITLE_BRUSHPANEL "###brushpanel"
#define TITLE_LSYSTEMPANEL "###lsystempanel"
#define TITLE_ANIMATION_SETTINGS "###animationpanel"
#define TITLE_SCRIPT_EDITOR "###scripteditor"
#define TITLE_SCENE_SETTINGS "###scenesettings"
#define TITLE_HELP "###help"
#define TITLE_OPTIONS "###optionspanel"

#define POPUP_TITLE_SCENEGRAPHDRAGANDDROP "##scenegraphdraganddroppopup"
#define POPUP_TITLE_UNSAVED "###unsavedpopup"
#define POPUP_TITLE_NEW_SCENE "###newscenepopup"
#define POPUP_TITLE_FAILED_TO_SAVE "###failedtosavepopup"
#define POPUP_TITLE_UNSAVED_SCENE "###unsavedscenepopup"
#define POPUP_TITLE_MODEL_NODE_SETTINGS "###modelsettingspopup"
#define POPUP_TITLE_TIPOFTHEDAY "###tipofthedaypopup"
#define POPUP_TITLE_WELCOME "###welcomepopup"
#define POPUP_TITLE_MINECRAFTMAPPING "###minecraftmappingpopup"
#define POPUP_TITLE_VOLUME_SPLIT "###volumesplitpopup"
#define POPUP_TITLE_RENAME_NODE "###renamenodepopup"
#define POPUP_TITLE_CREATE_ANIMATION "###createanimationpopup"
#define POPUP_TITLE_MODEL_UNREFERENCE "###unreferencedmodelpopup"
#define POPUP_TITLE_LOAD_PALETTE "###selectpalettepopup"
#define POPUP_TITLE_UV_EDITOR "###uveditorpopup"
